"""
Unique prose descriptions for Austria's 15 largest reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.
Austria's dams are primarily high-altitude Alpine storage reservoirs built
for hydroelectric power generation by utilities such as VERBUND and Illwerke vkw.
"""
from __future__ import annotations

AT_DAM_DESCRIPTIONS: dict[str, str] = {
    "Kolnbrein": (
        "The Kölnbrein Dam is Austria's largest reservoir and one of the most "
        "impressive engineering achievements in the Alps. Completed in 1978 on "
        "the Malta River in the Hohe Tauern range of Carinthia, the double-curvature "
        "arch dam stands 200 metres tall — making it the tallest dam in Austria — and "
        "holds 200 million cubic metres of water at 1,902 metres above sea level. "
        "The dam is the centrepiece of the Malta-Reisseck power plant complex operated "
        "by VERBUND, one of Europe's leading hydroelectric utilities. Water released "
        "from the reservoir plunges through a system of underground tunnels and "
        "powerhouses, generating renewable electricity for hundreds of thousands of "
        "Austrian households. The Kölnbrein reservoir and the surrounding Malta valley "
        "attract visitors who drive the spectacular Malta High Alpine Road, passing "
        "waterfalls, glaciers, and the sheer concrete face of the dam itself. The "
        "reservoir regularly stores snowmelt from winter precipitation, providing "
        "a critical seasonal buffer for the national electricity grid. The dam's "
        "construction required innovative engineering: the original thin arch design "
        "developed cracks under hydraulic pressure, necessitating a downstream "
        "concrete plinth added in 1992 to stabilise the structure — a well-documented "
        "chapter in Austrian dam engineering history."
    ),
    "Gepatsch": (
        "The Gepatsch Reservoir in the Kaunertal valley of North Tyrol is Austria's "
        "second-largest reservoir by storage capacity, holding 139 million cubic metres "
        "at an elevation of 1,767 metres above sea level. The rockfill dam, completed "
        "in 1964 on the Fagge River, stands 153 metres tall and is the cornerstone of "
        "the TIWAG (Tiroler Wasserkraft) hydropower system in the Ötztal Alps. Glacial "
        "meltwater from the surrounding Weißkamm mountains, including contributions "
        "from the Weißseeferner glacier, flows into the reservoir each summer, providing "
        "a reliable and renewable energy source. The Gepatsch pumped-storage system "
        "allows surplus electricity to be used to pump water back uphill at night, "
        "effectively acting as a giant battery for the Austrian grid. The Kaunertal "
        "Glacier Road, one of Austria's highest alpine roads, passes alongside the "
        "reservoir and draws both skiers and summer tourists. The dam's earth and "
        "rockfill construction was chosen to withstand the seismic activity common "
        "in this part of the eastern Alps."
    ),
    "Schlegeis": (
        "The Schlegeis Reservoir sits at 1,782 metres above sea level in the Zillertal "
        "Alps of Tyrol, cradled between peaks exceeding 3,000 metres. The double-arch "
        "dam completed in 1971 rises 131 metres and stores 126 million cubic metres "
        "of glacial and snowmelt water from the Zamser Bach and surrounding cirques. "
        "Operated by Verbund Hydro Power, Schlegeis is part of an integrated system "
        "that includes underground penstock tunnels and powerhouses in the valley below. "
        "The reservoir's turquoise colour — a result of fine glacial silt called "
        "rock flour — makes it one of the most photographed alpine lakes in Austria. "
        "A panoramic road along the southern shore provides access to hiking trails "
        "leading to the Hochfeiler and Olperer glacier regions. Climate change is "
        "slowly reducing the glacial contribution to the reservoir's annual inflow, "
        "making efficient seasonal storage increasingly important. The dam was designed "
        "to withstand the dynamic loads of avalanche pressure and ice formation "
        "during the long Tyrolean winter."
    ),
    "Zillergrundl": (
        "The Zillergründl Dam in the Zillertal Alps of Tyrol is one of Austria's "
        "highest arch dams, completed in 1987 at an altitude of approximately 1,550 "
        "metres. The double-curvature arch structure stands 186 metres tall and impounds "
        "90 million cubic metres from the upper Ziller catchment. Owned and operated "
        "by Zillertal Strom (a Verbund subsidiary), the reservoir feeds an underground "
        "powerhouse system that generates peak-load electricity for the Austrian grid. "
        "Water from the neighbouring Zillergrund reservoir can be pumped uphill into "
        "Zillergründl, giving the system pump-storage capability. The surrounding "
        "landscape is dominated by the Hochzillertal ski area and popular summer "
        "hiking terrain. The dam's construction in the late 1980s required advanced "
        "alpine logistics: all concrete was mixed on site in a batching plant above "
        "the valley floor, and workers were transported by cable car during winter. "
        "The reservoir's name — using the diminutive 'l' — reflects local dialect "
        "and distinguishes it from the adjacent Zillergrund reservoir completed a year "
        "earlier in 1986."
    ),
    "Zillergrund": (
        "The Zillergrund Reservoir in the Zillertal Alps of Tyrol was completed in "
        "1986 and works in close hydrological partnership with the neighbouring "
        "Zillergründl reservoir. The 186-metre arch dam impounds 85 million cubic "
        "metres from the upper Ziller River tributaries. Together the two Ziller "
        "reservoirs form a pump-storage system where water can be transferred between "
        "basins to optimise electricity generation against demand. The Zillertal valley "
        "is one of Austria's most visited alpine destinations, and the reservoir lies "
        "within hiking distance of several high-altitude refuges. The dam's construction "
        "coincided with the major expansion of Austria's hydroelectric capacity in the "
        "1980s, a decade that saw significant investment in pumped storage to balance "
        "the emerging nuclear phase-out policy. The Ziller catchment's high snowfall "
        "and glacial cover ensure reliable annual inflows, though climate projections "
        "indicate a gradual reduction in glacier-derived water over the coming decades. "
        "The reservoir supports important Alpine ecosystem services, including habitat "
        "for the Alpine ibex population reintroduced to the Zillertaler Alps in the "
        "twentieth century."
    ),
    "Limberg": (
        "The Limberg Reservoir is part of the legendary Kaprun hydropower complex in "
        "the state of Salzburg, built in the years following World War II as a symbol "
        "of Austrian reconstruction. The arch dam, completed in 1951, stands 120 metres "
        "tall and stores 85 million cubic metres at 2,040 metres above sea level in "
        "the Hohe Tauern. Together with the Mooserboden reservoir above it, Limberg "
        "forms a two-stage system for VERBUND's Kaprun pumped-storage plant. Water "
        "descends from Mooserboden into Limberg and then further down to the valley "
        "powerhouse near the town of Kaprun, generating electricity at multiple stages. "
        "The project is celebrated as a monument to post-war engineering effort: "
        "thousands of workers, many of them prisoners of war, laboured in extreme "
        "alpine conditions to build the dams and tunnels. A gondola tourist attraction "
        "now runs to the reservoir area, making the Kaprun complex one of Austria's "
        "most visited industrial heritage sites. The reservoir's elevation and aspect "
        "mean it typically retains ice cover from November through May."
    ),
    "Mooserboden": (
        "The Mooserboden Reservoir sits at a breathtaking 2,036 metres above sea level "
        "in the Hohe Tauern near Kaprun, Salzburg. Completed in 1955 — four years "
        "after the Limberg dam below it — the 107-metre arch dam stores 85 million "
        "cubic metres and forms the upper stage of VERBUND's world-famous Kaprun "
        "pumped-storage system. Water flows from Mooserboden down to Limberg and "
        "then to the valley powerhouse, enabling three-stage electricity generation. "
        "During periods of surplus electricity — particularly at night — pumps reverse "
        "the flow, lifting water back to Mooserboden to store energy for peak demand. "
        "The reservoir is flanked by the Hohe Tauern's jagged ridgeline; the Kitzsteinhorn "
        "glacier, visible from the dam, feeds snowmelt into both basins. The Kaprun "
        "hydroelectric scheme, including Mooserboden and Limberg, was constructed "
        "largely by Austrian forced labourers and prisoners of war between 1938 and "
        "1955, a complex history that the Kaprun Documentation Centre commemorates."
    ),
    "Lunersee": (
        "The Lünersee in Vorarlberg is Austria's largest natural alpine lake, elevated "
        "to reservoir status in 1959 when a 32-metre concrete dam was built at its "
        "outlet, raising the water level and more than doubling the lake's natural "
        "storage capacity to 78 million cubic metres. Situated at 1,970 metres in "
        "the Rätikon massif above Brand, the reservoir is operated by Illwerke vkw "
        "(a Vorarlberg utility) as part of the Lünersee-Latschau pump-storage system. "
        "During the skiing season, surplus overnight electricity from the European "
        "grid pumps water uphill to refill the reservoir; in daytime peak hours, "
        "the water descends to the Latschau powerhouse to meet demand. The Lünersee "
        "is accessible by cable car from Brand and is a popular summer destination "
        "for hikers exploring the surrounding Rätikon peaks, including the Three "
        "Sisters massif. The reservoir's clear, cold water and dramatic mountain "
        "backdrop make it one of the most scenic spots in western Austria, attracting "
        "visitors who combine the energy infrastructure tour with alpine recreation."
    ),
    "Stausee Ottenstein": (
        "The Ottenstein Reservoir is unusual among Austria's large dams because it "
        "lies not in the Alps but in the Waldviertel, the forested plateau of Lower "
        "Austria. The gravity dam, completed in 1957 on the Kamp River, stands 69 "
        "metres tall and stores 64 million cubic metres in a landscape of gentle "
        "hills, granite outcrops, and dense pine forest. The reservoir is part of "
        "the Kamp cascade, a chain of three hydroelectric reservoirs — Ottenstein, "
        "Dobra, and Thurnberg — operated by EVN (Energy-supply Lower Austria). "
        "Unlike the high-altitude alpine reservoirs, Ottenstein's primary purpose "
        "is run-of-river hydropower generation combined with flood control for the "
        "Kamp valley downstream. The area around the reservoir is a popular recreation "
        "zone for residents of Vienna, just 80 kilometres to the east, who come for "
        "sailing, fishing, cycling, and swimming in the reservoir's relatively warm "
        "lowland water. The Waldviertel's granite bedrock provides stable foundations "
        "for the dam and ensures excellent water quality in the reservoir."
    ),
    "Durlassboden": (
        "The Durlassboden Reservoir in the Gerlos valley of Tyrol stores snowmelt "
        "and rainfall from the Kitzbüheler Alps at an altitude of 1,244 metres. "
        "The 83-metre rockfill dam, completed in 1967, holds 53 million cubic metres "
        "and serves the Gerlos power scheme operated by TIWAG. Water from the reservoir "
        "flows through a pressure tunnel to a powerhouse in the Inn valley below, "
        "generating electricity throughout the year. The Gerlos Pass road — connecting "
        "Tyrol with the Salzburg region — runs past the reservoir, making it "
        "accessible to visitors exploring the region. The catchment includes parts "
        "of the Hohe Tauern National Park, and the Krimml Waterfalls — Europe's "
        "highest waterfalls — drain into the same hydrological system. The rockfill "
        "construction technique was chosen for its adaptability to the local geology "
        "of glacial moraine and weathered crystalline rock. Durlassboden plays "
        "a seasonal balancing role: full after summer snowmelt, drawn down over "
        "winter to meet heating-driven electricity demand across Tyrol."
    ),
    "Kopssee": (
        "The Kops Reservoir in the Montafon valley of Vorarlberg sits at 1,809 metres "
        "above sea level among some of the highest peaks in western Austria. The "
        "122-metre arch dam, completed in 1969, stores 43 million cubic metres from "
        "the upper Ill catchment and is part of Illwerke vkw's extensive Vorarlberg "
        "pumped-storage network. The Kops II expansion, completed in 2008, added a "
        "new powerhouse and pump turbines that significantly increased the system's "
        "flexibility for grid balancing. Together, the original Kops facility and "
        "Kops II can respond to changes in electricity demand within minutes, making "
        "the Kopssee system a key contributor to European grid stability. The "
        "surrounding Silvretta Alps offer world-class ski terrain in winter and "
        "glacier trekking routes in summer. The reservoir has a distinctive emerald "
        "colour from glacial flour suspended in the meltwater, and its surface "
        "frequently freezes over from December through April, requiring ice management "
        "procedures before the spring inflow season."
    ),
    "Silvretta": (
        "The Silvretta Reservoir straddles the border between Vorarlberg and Tyrol "
        "in the heart of the Silvretta massif, one of the most glaciated ranges in "
        "the eastern Alps. The 80-metre arch dam, completed in 1943 on the Ill River, "
        "stores 38 million cubic metres at 2,030 metres above sea level. It is one "
        "of Austria's oldest major alpine dams, constructed during World War II to "
        "supply hydroelectric power to the German war economy. Today the reservoir "
        "is part of Illwerke vkw's integrated Vorarlberg energy system. The Silvretta "
        "Hochalpenstrasse — a high mountain toll road open only in summer — leads "
        "directly to the reservoir, making it one of the most accessible high-altitude "
        "lakes in Austria. The area is famous for the Silvretta glacier panorama "
        "and serves as a staging point for ascents of the Piz Buin (3,312 m), the "
        "highest peak in Vorarlberg. The reservoir lies within the Silvretta Nature "
        "Reserve, where strict environmental regulations protect the fragile Alpine "
        "ecosystem around the dam."
    ),
    "Tauernmoossee": (
        "The Tauernmoossee is a relatively small but strategically placed reservoir "
        "in the Stubachtal valley of Salzburg, completed in 1988 at 1,684 metres "
        "above sea level. The 28-metre rockfill dam stores 13 million cubic metres "
        "and acts as the upper collecting basin for the Stubachwerk hydropower scheme "
        "operated by Salzburg AG. The reservoir collects snowmelt and runoff from "
        "the Granatspitzgruppe, a section of the Hohe Tauern known for its garnet "
        "deposits — the Stubachtal is sometimes called 'Garnet Valley'. Water flows "
        "through underground galleries to the Enzingerboden reservoir below and "
        "ultimately to the Uttendorf powerhouse in the Salzach valley. The reservoir "
        "lies within the Hohe Tauern National Park, Austria's largest protected area, "
        "and its construction required careful environmental planning. The Tauernmoossee "
        "contributes to the seasonal regulation of the Stubache tributary, reducing "
        "peak flood risk downstream while enabling year-round power generation from "
        "a catchment with some of Austria's highest snowfall totals."
    ),
    "Vermunt": (
        "The Vermunt Reservoir in the Montafon valley of Vorarlberg holds the "
        "distinction of being one of Austria's oldest hydroelectric storage dams, "
        "completed in 1930 when high-alpine dam engineering was still in its early "
        "decades. The 38-metre arch dam stores 12 million cubic metres on the Ill "
        "River at 1,743 metres above sea level. As part of the Illwerke vkw system, "
        "Vermunt collects water from the upper Ill catchment and feeds the Partenen "
        "powerhouse below. The reservoir was expanded and reinforced several times "
        "over the decades as the Montafon power system grew around it. Despite its "
        "modest capacity compared to neighbouring reservoirs like Kopssee and "
        "Silvretta, Vermunt plays a critical role in daily flow regulation. The "
        "Bielerhöhe pass, where the famous Silvretta Hochalpenstrasse begins, "
        "lies just above the Vermunt basin and is a popular summer destination "
        "for cyclists and motorists. The reservoir's nearly century-old dam is "
        "a testament to early twentieth-century alpine civil engineering, built "
        "at a time when workers had to ascend on foot with hand tools."
    ),
    "Drossen": (
        "The Drossen Reservoir is one of the smaller storage facilities in the "
        "Kaprun-Zell am See hydropower network in the state of Salzburg. The "
        "75-metre arch dam, completed in 1949, stores 4 million cubic metres "
        "in a steep side valley of the Salzach tributary system at approximately "
        "1,050 metres above sea level. Drossen functions as a compensating basin "
        "within VERBUND's multi-stage power plant cascade, evening out the flow "
        "from larger upstream reservoirs before discharge to the valley floor. "
        "Despite its relatively small volume, the dam's 75-metre height reflects "
        "the steep topography of the Salzburg Alps, where narrow gorges can "
        "impound significant head with modest reservoir surface area. The Drossen "
        "reservoir is not generally accessible to the public but is visible from "
        "mountain paths in the surrounding Hohe Tauern foothills. The name "
        "derives from the local toponym for the stream valley, a common pattern "
        "in the Austrian alpine naming tradition where infrastructure takes the "
        "name of the nearest natural feature."
    ),
}


def get_at_dam_description(name_en: str) -> str:
    """Return the description for an Austrian dam, or a generic fallback.

    The fallback ensures the dam detail page always has body text even when
    a bespoke description has not yet been written.
    """
    return AT_DAM_DESCRIPTIONS.get(
        name_en,
        (
            f"{name_en} is one of Austria's important Alpine reservoirs, "
            "primarily used for hydroelectric power generation in the "
            "high-altitude mountain environment of the eastern Alps. "
            "The dam contributes to Austria's renewable energy network, "
            "which generates more than 60 per cent of national electricity "
            "from hydroelectric sources."
        ),
    )
