"""
Unique prose descriptions for Bulgaria's 20 largest reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.

Each description covers: location, river basin, capacity, and primary purpose
(water supply, irrigation, hydropower, or multi-purpose). Word count: 200–250.
"""
from __future__ import annotations

BG_DAM_DESCRIPTIONS: dict[str, str] = {
    "Iskar": (
        "Iskar Reservoir is the largest dam in Bulgaria and the primary source of "
        "drinking water for the capital city Sofia, supplying approximately 1.2 million "
        "residents. Located in the western Balkan Mountains within the Iskar gorge, the "
        "dam was completed in 1954 and impounds the Iskar River, the longest river that "
        "rises and flows entirely within Bulgaria. With a total capacity of 655.3 MCM, "
        "Iskar Reservoir has shaped the water security of the Sofia metropolitan area "
        "for seven decades. The reservoir stretches for nearly 20 kilometres through a "
        "dramatic canyon and is fed by snowmelt from the Rila and Vitosha mountain "
        "ranges, giving it a reliable annual recharge cycle. The Iskar cascade below the "
        "dam includes several hydroelectric power stations that contribute to Bulgaria's "
        "electricity grid. The reservoir is also an important habitat for migrating "
        "waterbirds and supports recreational fishing. The dam structure is a concrete "
        "gravity type standing 74 metres high. Water managers prioritise domestic supply "
        "above all other uses, with irrigation and hydropower generation allocated from "
        "surplus storage. Sofia's water utility SOFIYSKA VODA monitors Iskar levels "
        "daily, and the reservoir's fill percentage is closely watched during summer "
        "droughts as an indicator of the city's water security outlook for the coming "
        "months."
    ),
    "Ogosta": (
        "Ogosta Reservoir lies in northwestern Bulgaria near the town of Montana, "
        "impounding the Ogosta River in the foothills of the western Balkan Mountains. "
        "Completed in 1989 as one of the last large infrastructure projects of the "
        "communist era, Ogosta is the second largest reservoir in Bulgaria with a "
        "capacity of 506.0 MCM. Its primary purpose is to supply irrigation water for "
        "the fertile Danubian Plain agricultural region to the north, which is one of "
        "Bulgaria's most productive farming areas for grain and sunflowers. The dam also "
        "provides drinking water for Montana and surrounding municipalities, and its "
        "hydropower station generates electricity during periods of high storage. The "
        "reservoir basin spans a wide, gently rolling landscape with forested hills on "
        "its southern shore and agricultural land around its northern banks. Water "
        "releases are carefully managed throughout the growing season (April–September) "
        "to meet peak irrigation demand while maintaining minimum ecological flows in "
        "the lower Ogosta River. The reservoir is a favourite among anglers who prize "
        "its populations of pike, perch, and carp. Ogosta's catchment receives moderate "
        "precipitation of around 650 mm annually, supplemented by snowmelt from the "
        "adjacent Balkan Mountains in spring, which represents the most significant "
        "annual recharge event for this reservoir system."
    ),
    "Kardzhali": (
        "Kardzhali Reservoir is situated on the Arda River in the Eastern Rhodope "
        "Mountains in southern Bulgaria, near the regional centre of Kardzhali. "
        "Completed in 1953, it is one of Bulgaria's oldest large dams and occupies a "
        "dramatic position in a deep gorge carved by the Arda through ancient volcanic "
        "rock. With a capacity of 497.2 MCM it ranks third among Bulgarian reservoirs. "
        "The dam serves a triple purpose: drinking water supply for Kardzhali and "
        "downstream settlements, hydroelectric power generation, and flow regulation to "
        "protect lowland areas from seasonal floods. The Kardzhali hydropower station, "
        "integrated into the dam structure, has been a reliable producer of renewable "
        "electricity for over seventy years. The reservoir lies in a region of southern "
        "Bulgaria with a transitional Mediterranean climate, receiving warm, dry summers "
        "and mild, wet winters; the Arda catchment extends into the high Rhodopes where "
        "snowpack accumulates from December through March and provides a critical spring "
        "recharge pulse. The reservoir is a major recreational destination, with fishing, "
        "boating, and bird-watching popular along its long, fjord-like arms. It also "
        "plays an important role in Bulgaria's cascade of Arda River reservoirs — "
        "Kardzhali, Studen Kladenets, and Ivaylovgrad — that together regulate the "
        "entire lower Arda basin before it crosses into Greece."
    ),
    "Dospat": (
        "Dospat Reservoir lies in the Western Rhodope Mountains of southern Bulgaria, "
        "near the town of Dospat at an elevation of approximately 1,380 metres above sea "
        "level. The dam was completed in 1975 and impounds the Dospat River, a major "
        "tributary of the Arda system. At 449.2 MCM capacity, Dospat is the fourth "
        "largest reservoir in Bulgaria and occupies a distinctive high-altitude basin "
        "surrounded by dense Rhodope pine and spruce forests. Its primary use is "
        "hydropower generation: water from Dospat feeds the Tsankov Kamak and Vacha "
        "cascade below, enabling a significant head drop through a series of underground "
        "tunnels and penstocks to turbines situated hundreds of metres lower in the "
        "valleys. The Rhodope highland climate delivers substantial annual precipitation "
        "exceeding 1,000 mm, much of it falling as snow between November and April. The "
        "deep snowpack that accumulates in the surrounding mountains is the primary source "
        "of reservoir recharge, with melt typically completing by June. The reservoir is "
        "a popular destination for trout fishing and hiking in summer. The high-altitude "
        "location means Dospat is largely unaffected by summer evaporation losses that "
        "reduce storage in lower-elevation Bulgarian reservoirs, making it one of the "
        "most hydrologically reliable in the country's energy system."
    ),
    "Zhrebchevo": (
        "Zhrebchevo Reservoir is located on the Tundzha River in central Bulgaria, "
        "upstream of Sliven and Yambol in the Sredna Gora foothills. Completed in 1963, "
        "the reservoir has a total capacity of 400.0 MCM and serves as a multi-purpose "
        "facility providing irrigation water to the Rose Valley and Thracian Plain, "
        "drinking water supply to several municipalities, and hydropower generation. "
        "The Tundzha River rises in the eastern Stara Planina (Balkan Mountains) and "
        "receives inflows from numerous mountain tributaries, giving Zhrebchevo a "
        "relatively reliable hydrological regime compared to reservoirs in drier regions. "
        "The Rose Valley immediately downstream of the reservoir is famous worldwide for "
        "the cultivation of the Kazanlak rose, from which Bulgaria produces the majority "
        "of the world's rose oil. Zhrebchevo's irrigation releases play a direct role "
        "in sustaining this economically and culturally significant agricultural sector. "
        "The reservoir is also an important stopover for migratory birds following the "
        "Via Pontica flyway, and its shores host several protected wetland habitats. "
        "The surrounding landscape is characterised by oak and hornbeam forest on the "
        "hillsides and rich alluvial farmland near the water's edge. Zhrebchevo is "
        "managed as part of a cascade with the Koprinka Reservoir downstream on the same "
        "river system."
    ),
    "Studen Kladenets": (
        "Studen Kladenets Reservoir is the second dam in the Arda River cascade in "
        "southern Bulgaria, located between Kardzhali upstream and Ivaylovgrad downstream "
        "in the Eastern Rhodope Mountains. Completed in 1954, it has a storage capacity "
        "of 387.8 MCM. The reservoir occupies a deep, narrow gorge where the Arda has "
        "cut through ancient metamorphic and volcanic rocks, creating a sinuous water "
        "body with steeply forested banks. Its primary function is hydropower generation "
        "through the Studen Kladenets power station, which exploits the head difference "
        "between the regulated storage and the turbine outlet at a lower elevation. The "
        "reservoir also provides regulating storage for downstream irrigation withdrawals "
        "along the lower Arda in the Haskovo and Kardzhali regions. The Eastern Rhodope "
        "climate is warm and semi-arid; summer evaporation is a significant factor in "
        "the reservoir's seasonal water balance, and inflows are most reliable in winter "
        "and spring. The reservoir area is notable for its rich Thracian archaeological "
        "heritage — several ancient Thracian cult sites and rock sanctuaries are visible "
        "along the reservoir's shores. The surrounding Eastern Rhodopes are one of the "
        "most important zones in Europe for vulture conservation, with griffon, black, "
        "and Egyptian vultures nesting on the rocky cliffs above the water."
    ),
    "Tsonevo": (
        "Tsonevo Reservoir is located in northeastern Bulgaria in the foothills of the "
        "eastern Balkan Mountains, on the Luda Kamchiya River near the town of Dalgopol "
        "in Varna Province. Completed in 1971 with a storage capacity of 330.0 MCM, "
        "Tsonevo is the primary source of drinking water for the city of Varna — "
        "Bulgaria's largest Black Sea port and second largest city with approximately "
        "400,000 residents. The reservoir's drinking water supply function is paramount: "
        "releases for irrigation and hydropower are subordinated to the requirement to "
        "maintain safe minimum storage levels for municipal supply. The Luda Kamchiya "
        "catchment covers a large area of the eastern Balkan Mountains and receives "
        "moderate precipitation supplemented by substantial spring snowmelt. The "
        "reservoir basin is surrounded by mixed oak and hornbeam forests typical of "
        "northeastern Bulgaria, and the shoreline habitats support a variety of waterfowl "
        "and wetland species. The water travels from Tsonevo through a system of pipelines "
        "and treatment facilities before reaching Varna and the coastal resorts of the "
        "Riviera. Water supply planners in Varna monitor Tsonevo levels closely during "
        "the summer tourist season, when the coastal population swells with visitors and "
        "demand rises significantly above the winter baseline, creating periodic "
        "pressure on the reservoir's storage reserves."
    ),
    "Ticha": (
        "Ticha Reservoir is situated in northeastern Bulgaria on the Ticha River, a "
        "right-bank tributary of the Kamchiya system, within the eastern Balkan Mountains "
        "near the town of Shumen. The dam was completed in 1984 and has a capacity of "
        "311.8 MCM, making it one of the largest reservoirs in northeastern Bulgaria. "
        "Its principal functions are drinking water supply to Shumen, Targovishte, and "
        "several smaller towns in the Shumen and Targovishte regions, as well as "
        "irrigation supply for the Thracian Plain agricultural lands downstream. The "
        "reservoir is fed by the Ticha River and numerous smaller streams draining the "
        "eastern Stara Planina, which receives higher precipitation than the surrounding "
        "plains — the Balkan Mountains here intercept Atlantic and Mediterranean weather "
        "systems, producing reliable winter snowfall and spring melt. The reservoir "
        "landscape is characterised by beech and hornbeam forest on the northern slopes "
        "and more open terrain on the south-facing hillsides. Ticha is an important "
        "freshwater fishing location, prized for its carp and catfish populations. The "
        "water treatment infrastructure associated with Ticha is among the most modern "
        "in northeastern Bulgaria, having been upgraded in the 2000s to comply with "
        "European Union drinking water standards following Bulgaria's accession to the EU."
    ),
    "Batak": (
        "Batak Reservoir lies in the Western Rhodope Mountains of southern Bulgaria at "
        "an elevation of approximately 1,050 metres, near the town of Batak in Pazardzhik "
        "Province. Completed in 1954, it has a capacity of 310.3 MCM and sits within a "
        "broad alpine basin surrounded by Rhodope pine and spruce forests. The primary "
        "purpose of Batak is to serve as the upper storage reservoir for the Batachka "
        "hydropower cascade, which transfers water through a system of tunnels and "
        "penstocks down to the Tsarevets and Alabak power stations located hundreds of "
        "metres lower in the valleys. This makes Batak a critical asset in Bulgaria's "
        "hydropower energy system, capable of rapid response to peak electricity demand. "
        "The reservoir also supplies water for the Batak-Kaira irrigation system that "
        "serves agricultural land in the upper Maritsa basin. The high-altitude location "
        "gives Batak a climate with cold winters, significant snowfall between October "
        "and April, and relatively cool summers. Snowmelt is the dominant annual recharge "
        "mechanism. The pristine mountain environment around the reservoir makes it a "
        "popular destination for hiking and fishing tourism in summer. The Batak area is "
        "also notable as the site of a major historical event — the 1876 April Uprising "
        "massacre — which is commemorated in the town museum nearby."
    ),
    "Kamchia": (
        "Kamchia Reservoir is located in northeastern Bulgaria on the Kamchiya River, "
        "one of the largest rivers flowing into the Bulgarian Black Sea coast. The dam "
        "is situated near the village of Kamchiya in Varna Province and was completed in "
        "1975. With a storage capacity of 233.6 MCM, the reservoir serves multiple "
        "purposes: irrigation supply for agricultural lands in the Varna and Shumen "
        "regions, industrial water supply, and compensation flow regulation into the "
        "lower Kamchiya River. The Kamchiya estuary downstream of the dam is one of "
        "Bulgaria's most important protected natural areas — the Kamchia Biosphere "
        "Reserve and its unique longoz (flooded riparian) forest, which shelters over "
        "150 bird species. Water managers must balance agricultural extraction against "
        "the ecological flow requirements of this internationally recognised wetland "
        "system. The reservoir catchment covers a large area of the eastern Balkan "
        "Mountains and receives moderate precipitation. The surrounding landscape is "
        "largely agricultural — cereal crops, sunflowers, and vineyards — with forested "
        "ridges rising to the south. Kamchia is an important freshwater fishing location, "
        "and its shores are popular with recreational visitors from the nearby coastal "
        "resorts of the Black Sea riviera during the summer season."
    ),
    "Vacha": (
        "Vacha Reservoir occupies a dramatic gorge on the Vacha River in the western "
        "Rhodope Mountains of southern Bulgaria, near the town of Krichim in Plovdiv "
        "Province. Completed in 1974, the dam stands 141 metres high — one of the "
        "tallest dams in Bulgaria — and has a storage capacity of 226.1 MCM. Vacha is "
        "the centrepiece of one of Bulgaria's most important hydropower cascades, which "
        "includes the Dospat, Tsankov Kamak, and Vacha reservoirs linked by a system of "
        "tunnels and underground power stations. The Vacha hydropower station exploits "
        "the significant head between the reservoir surface and the Thracian Plain below, "
        "generating substantial quantities of renewable electricity. The reservoir also "
        "serves as the primary water supply source for the city of Plovdiv — Bulgaria's "
        "second largest city with approximately 350,000 residents — via the Vacha-Plovdiv "
        "aqueduct. Water from Vacha is also used for irrigation in the upper Maritsa "
        "valley. The gorge setting gives Vacha a striking visual character; the steep, "
        "forested canyon walls plunge hundreds of metres to the water surface below. "
        "The western Rhodope climate delivers high annual precipitation exceeding 900 mm, "
        "and the reservoir benefits from a reliable snowmelt recharge each spring from "
        "the adjacent high Rhodope plateaux."
    ),
    "Pyasachnik": (
        "Pyasachnik Reservoir is located on the Topolnitsa River in central Bulgaria, "
        "in the foothills of the central Sredna Gora mountain range in Plovdiv Province. "
        "Completed in 1977 with a capacity of 206.5 MCM, it is one of three reservoirs "
        "on the Topolnitsa River — together with Stamboliyski downstream and Topolnitsa "
        "upstream — that form a cascade for water supply and irrigation management in "
        "the upper Maritsa catchment. Pyasachnik's primary purpose is irrigation water "
        "supply to agricultural areas in the Pazardzhik and Plovdiv regions, supplemented "
        "by contributions to municipal water supply. The Topolnitsa River drains a "
        "predominantly agricultural and forested catchment in the northern flanks of "
        "Sredna Gora, receiving moderate precipitation with a spring peak corresponding "
        "to snowmelt from the higher elevations. The reservoir is situated in a broad "
        "valley with rolling hills on all sides, and its shores are bordered by mixed "
        "oak and riverine vegetation. Pyasachnik is a popular recreational destination "
        "within easy reach of Plovdiv, Bulgaria's second city, offering fishing, "
        "boating, and picnicking facilities. The reservoir also provides a degree of "
        "flood regulation for the Topolnitsa valley, attenuating peak flows during the "
        "high-rainfall months of November through March."
    ),
    "Stamboliyski": (
        "Stamboliyski Reservoir is situated on the Maritsa River near the town of "
        "Stamboliyski in Plovdiv Province, central Bulgaria. Completed in 1963 with a "
        "capacity of 205.6 MCM, the reservoir is one of the few major dams on the main "
        "course of the Maritsa — Bulgaria's longest river and the principal river of "
        "the Thracian Plain. Its primary functions are irrigation supply for the highly "
        "productive agricultural lands of the Upper Thracian Plain, drinking water "
        "provision to several municipalities in the Plovdiv region, and industrial water "
        "supply for factories in the Maritsa Industrial Zone. The reservoir also "
        "provides important flood protection for downstream communities during the "
        "Maritsa's spring flood peaks. The Maritsa at this point receives inflows from "
        "the Rhodope Mountains to the south and the Sredna Gora range to the north, "
        "giving it a large and hydrologically diverse catchment. The reservoir landscape "
        "is characterised by flat, intensively cultivated agricultural plains on the "
        "northern shore and more rolling terrain with vineyards and orchards to the "
        "south. Stamboliyski lies within the greater Plovdiv metropolitan area and is "
        "important for the water security of one of Bulgaria's most economically "
        "dynamic regions, home to significant manufacturing and agro-industrial activity."
    ),
    "Ivaylovgrad": (
        "Ivaylovgrad Reservoir is the third and most downstream dam in the Arda River "
        "cascade in southern Bulgaria, near the town of Ivaylovgrad in Haskovo Province, "
        "close to the Greek border. Completed in 1959 with a capacity of 156.7 MCM, "
        "Ivaylovgrad regulates the final stretch of the Bulgarian Arda before the river "
        "crosses into Greece and eventually joins the Evros (Maritsa) at the Aegean. "
        "The reservoir's primary purpose is hydropower generation through the Ivaylovgrad "
        "power station, which benefits from the accumulated head drop of the full Arda "
        "cascade. It also provides irrigation water for the Haskovo and Kardzhali "
        "regions and delivers minimum ecological flows to Greece under a bilateral water "
        "agreement. The Eastern Rhodope landscape around Ivaylovgrad is among the warmest "
        "and driest in Bulgaria, with a transitional Mediterranean climate. The rocky "
        "hills above the reservoir are renowned for their exceptional biodiversity: the "
        "Eastern Rhodopes host the largest population of breeding vultures in Bulgaria "
        "and one of the most important in Europe, including griffon, black, and Egyptian "
        "vultures. The reservoir shoreline and surrounding scrubland are designated as "
        "protected areas under both Bulgarian law and the EU Natura 2000 network."
    ),
    "Belmeken": (
        "Belmeken Reservoir sits at an elevation of approximately 1,900 metres in the "
        "Rila Mountains of southwestern Bulgaria, near the Belmeken saddle in Pazardzhik "
        "Province. Completed in 1967 with a capacity of 144.0 MCM, Belmeken is the "
        "highest reservoir in Bulgaria and occupies one of the most spectacular alpine "
        "settings in the Balkans. It forms the upper storage element of the Belmeken-"
        "Sestrimo hydropower cascade, which transfers water through a 9-kilometre tunnel "
        "and underground penstocks to the Sestrimo power station located over 700 metres "
        "lower in the Maritsa valley. This enormous head difference makes the Belmeken-"
        "Sestrimo complex one of the highest-capacity hydropower installations in Bulgaria "
        "and a critical resource for peak electricity generation. The reservoir is "
        "refilled by snowmelt from the surrounding Rila peaks, many of which exceed "
        "2,500 metres; the snowpack persists until June or even July in high-altitude "
        "basins. The high-alpine climate means the reservoir is frozen for several months "
        "in winter, limiting pumped storage operations. The area around Belmeken is part "
        "of the Rila National Park, one of Bulgaria's most protected and biologically "
        "rich mountain areas. Access is restricted in winter, when snow conditions make "
        "the mountain roads impassable."
    ),
    "Koprinka": (
        "Koprinka Reservoir lies in the famous Rose Valley of central Bulgaria, on the "
        "Tundzha River near the town of Kazanlak in Stara Zagora Province. Completed in "
        "1955 with a capacity of 142.2 MCM, Koprinka is historically notable as the "
        "reservoir that inundated the ancient Thracian city of Seuthopolis — capital of "
        "the Odrysian Thracian king Seuthes III — which now lies submerged beneath its "
        "waters. The reservoir provides irrigation water for the Rose Valley's renowned "
        "Rosa damascena cultivation, drinking water for Kazanlak and surrounding "
        "municipalities, and a degree of flood protection for the middle Tundzha valley. "
        "The Rose Valley's unique microclimate — protected by the Stara Planina to the "
        "north and the Sredna Gora to the south, with cool mornings and warm afternoons "
        "in May — is ideal for rose cultivation, and irrigation from Koprinka is "
        "essential to maintain this tradition. The reservoir is also important for "
        "tomato, grain, and other vegetable cultivation in the surrounding plains. "
        "Plans have periodically been revived to construct a glass dome over the "
        "submerged Seuthopolis site, which would allow the archaeological remains to "
        "be accessed while the reservoir continues to operate. Koprinka is part of the "
        "Tundzha cascade that includes Zhrebchevo upstream."
    ),
    "Topolnitsa": (
        "Topolnitsa Reservoir is located on the Topolnitsa River in Plovdiv Province, "
        "central Bulgaria, upstream of the larger Pyasachnik Reservoir. Completed in "
        "1979 with a capacity of 137.1 MCM, the reservoir serves primarily as an "
        "irrigation storage facility for the agricultural region of Pazardzhik, "
        "supplementing water supply to settlements in the upper Topolnitsa valley and "
        "providing some degree of flood regulation. The Topolnitsa River drains the "
        "southern slopes of Sredna Gora and receives moderate annual precipitation of "
        "around 650–700 mm, with a distinct spring peak driven by snowmelt. The "
        "reservoir basin is surrounded by mixed deciduous forest and agricultural land, "
        "with the cultivated Thracian Plain opening out downstream. As the uppermost "
        "reservoir in the Topolnitsa cascade, Topolnitsa acts as a seasonal buffer, "
        "storing spring inflows for release during the dry summer irrigation season "
        "when Topolnitsa River base flows are insufficient to meet demand. The reservoir "
        "supports a recreational fishing community and provides a tranquil green space "
        "for residents of the Pazardzhik region. Water quality in the Topolnitsa system "
        "is closely monitored by the Basin Directorate of the Eastern Aegean basin, "
        "which oversees the integrated management of the Maritsa-Topolnitsa sub-basin "
        "in accordance with the EU Water Framework Directive."
    ),
    "Gorni Dabnik": (
        "Gorni Dabnik Reservoir is located in northern Bulgaria on the Vit River, a "
        "right-bank tributary of the Danube, near the town of Gorni Dabnik in Pleven "
        "Province. Completed in 1971 with a capacity of 130.0 MCM, the reservoir "
        "provides irrigation water for the fertile agricultural plains of the Pleven "
        "region, one of Bulgaria's most important cereal and sunflower growing areas. "
        "The Vit River drains the central Balkan Mountains and enters the Danubian Plain "
        "at the foothills north of Lovech, providing a reliable catchment with moderate "
        "precipitation and significant spring snowmelt. The reservoir basin is set in a "
        "gentle, rolling landscape typical of northern Bulgaria's Danubian Plateau, with "
        "agricultural fields stretching to the horizon and occasional windbreaks of "
        "poplar and willow. Gorni Dabnik also supplies drinking water to several "
        "municipalities in the Pleven and Lovech regions and provides industrial water "
        "to facilities in the area. The reservoir is managed in coordination with the "
        "Yablanitsa, Orsoya, and other smaller dams in the Pleven sub-basin to optimise "
        "water allocation across the agricultural season. The surrounding area is "
        "historically significant as the site of the 1877 Battle of Gorni Dubnik during "
        "the Russo-Turkish War, and a memorial park commemorates the Russian and Finnish "
        "soldiers who fought there during Bulgaria's liberation."
    ),
    "Trakiets": (
        "Trakiets Reservoir is situated on the Maritsa River in southern Bulgaria near "
        "the village of Trakiets in Haskovo Province. Completed in 1961 with a capacity "
        "of 114.0 MCM, the reservoir was constructed primarily for irrigation purposes "
        "to serve the agricultural lands of the Upper Thracian Plain and Haskovo Region. "
        "The Maritsa at this point is one of the larger rivers of the Balkan Peninsula, "
        "flowing across a broad alluvial plain before crossing into Turkey and eventually "
        "reaching the Aegean Sea. Trakiets provides irrigation water for a productive "
        "agricultural zone where cotton, tobacco, grain, and vegetables are widely "
        "cultivated. It also contributes to drinking water supply for Haskovo and "
        "neighbouring towns and provides industrial water to the Haskovo industrial zone. "
        "The reservoir is a popular angling destination, hosting regular freshwater "
        "fishing competitions. The surrounding Thracian Plain landscape is characterised "
        "by its flat terrain, warm continental climate with hot summers, and high "
        "summer water demand that places considerable pressure on the reservoir during "
        "drought years. The reservoir name reflects the region's deep Thracian "
        "archaeological heritage: the Upper Thracian Plain and Eastern Rhodopes around "
        "Haskovo contain numerous ancient Thracian tombs, treasure hoards, and cult "
        "sites, some of outstanding European significance."
    ),
    "Tsankov Kamak": (
        "Tsankov Kamak Reservoir is the newest large dam in Bulgaria, completed in 2012 "
        "on the Vacha River in the Western Rhodope Mountains of Plovdiv Province. With "
        "a dam height of 130 metres and a storage capacity of 110.7 MCM, Tsankov Kamak "
        "occupies a narrow, steep gorge carved by the Vacha River through ancient granite "
        "and gneiss bedrock. It functions as an intermediate storage reservoir in the "
        "Dospat-Tsankov Kamak-Vacha hydropower cascade, receiving water released from "
        "the Dospat Reservoir above and in turn releasing to the Vacha Reservoir below. "
        "The cascade system enables flexible scheduling of electricity generation across "
        "all three reservoirs, maximising the economic value of the stored water through "
        "peak-time discharge. Construction of Tsankov Kamak was controversial due to its "
        "location within the Rhodope Mountains, a region with significant environmental "
        "and cultural sensitivity. The reservoir flooded part of a valley used by "
        "local Rhodope communities and prompted lengthy public debate about the balance "
        "between renewable energy development and landscape conservation. The Rhodope "
        "Mountains around Tsankov Kamak receive substantial precipitation exceeding "
        "900 mm annually, with deep winter snowpack ensuring reliable spring recharge "
        "for the entire cascade system. The dam is operated by the Bulgarian Energy "
        "Holding as part of its portfolio of Rhodope hydropower assets."
    ),
}


def get_bg_dam_description(name_en: str) -> str:
    """Return the prose description for a Bulgarian reservoir, or a generic fallback."""
    return BG_DAM_DESCRIPTIONS.get(
        name_en,
        f"{name_en} is one of Bulgaria's major reservoirs, monitored by the Ministry "
        f"of Environment and Water (MOEW). It plays an important role in the country's "
        f"water supply, irrigation, and hydropower systems in the broader Balkan region.",
    )
