"""
Unique prose descriptions for Czech Republic's 15 largest reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.
"""
from __future__ import annotations

CZ_DAM_DESCRIPTIONS: dict[str, str] = {
    "Orlik": (
        "Orlík is the largest reservoir in the Czech Republic, impounding 716 million "
        "cubic metres on the Vltava River in southern Bohemia. The concrete gravity dam "
        "stands 91 metres tall and was completed in 1963 as the centrepiece of the "
        "Vltava Cascade — a chain of interconnected reservoirs that together form one of "
        "Central Europe's most ambitious hydroelectric systems. The dam's primary purpose "
        "is hydroelectric power generation, providing a significant share of the Czech "
        "national grid's renewable capacity. The reservoir stretches approximately 68 "
        "kilometres upstream into the Bohemian highlands, creating a serpentine lake "
        "of remarkable beauty flanked by forested slopes and dramatic cliff faces. "
        "The flooding of the Orlík valley in the early 1960s required the relocation "
        "of several villages and the medieval Orlík Castle was raised on a rocky outcrop "
        "that now forms a peninsula above the water. Today the reservoir is a major "
        "recreational destination for sailing, windsurfing, and cycling along its shores, "
        "attracting hundreds of thousands of visitors each year from Prague and beyond."
    ),
    "Lipno": (
        "Lipno is Czech Republic's second-largest reservoir by volume and the largest "
        "by surface area, covering approximately 48.7 square kilometres in the South "
        "Bohemian Region near the Austrian border. Completed in 1959 on the Vltava "
        "River close to its source in the Šumava Mountains, the concrete gravity dam "
        "is 25 metres tall and holds 306 million cubic metres. The reservoir's "
        "shallow character and vast surface make it exceptionally warm in summer, "
        "earning it the nickname 'the South Bohemian Sea.' The area is a premier "
        "leisure destination with extensive facilities for swimming, sailing, "
        "windsurfing, and cycling along the adjacent Greenways trail. The Šumava "
        "National Park borders the reservoir's southern shore, blending water "
        "recreation with pristine forest wilderness. Lipno's hydroelectric plant "
        "contributes to the regional energy supply, while the reservoir also helps "
        "regulate seasonal flooding along the lower Vltava."
    ),
    "Nechranice": (
        "Nechranice is the largest reservoir in northwestern Bohemia and one of the "
        "most important water supply sources in the Czech Republic. Located on the "
        "Ohře River in the Ústí nad Labem Region, the earthfill dam was completed "
        "in 1968 and holds 288 million cubic metres behind a structure 48 metres "
        "tall. Its primary role is drinking water supply for the heavily industrialised "
        "towns of northwestern Bohemia, including Chomutov, Most, and the broader "
        "Ústecký Region. The reservoir also provides cooling water for the Tušimice "
        "and Prunéřov thermal power stations nearby. Unlike many Czech reservoirs, "
        "Nechranice does not rely primarily on hydroelectric generation. The "
        "surrounding landscape bears the marks of centuries of coal mining and heavy "
        "industry, making the reservoir an important natural amenity and ecological "
        "corridor. In recent decades, the area around Nechranice has been developed "
        "for recreation, with a marina and beaches attracting visitors seeking respite "
        "from the industrial setting."
    ),
    "Slapy": (
        "Slapy Reservoir sits on the Vltava River approximately 40 kilometres south "
        "of Prague, making it the most accessible large reservoir to the Czech capital "
        "and the most visited recreational water body in the country. The concrete "
        "gravity dam was completed in 1955 and stands 67 metres tall, impounding "
        "270 million cubic metres. As part of the Vltava Cascade, Slapy serves both "
        "hydroelectric generation and flood control for Prague downstream. The reservoir "
        "stretches over 42 kilometres and is flanked by steep wooded hills cut through "
        "by the ancient Vltava valley. On summer weekends the shores teem with "
        "campers, boaters, and swimmers, while the calmer spring and autumn months "
        "attract anglers and hikers. The historic town of Štěchovice sits near the "
        "dam's base, and several riverside villages survived the flooding, their "
        "church spires visible above the waterline. Slapy is also home to one of "
        "the longest natural swimming areas in Bohemia."
    ),
    "Svihov": (
        "Švihov Reservoir on the Želivka River is the most strategically critical "
        "water source in the Czech Republic, supplying drinking water to Prague "
        "and central Bohemia — together serving approximately 1.2 million people. "
        "The earthfill dam was completed in 1975, stands 58 metres tall, and holds "
        "267 million cubic metres. Due to its vital role in public water supply, "
        "the reservoir operates under strict protection: swimming, boating, and "
        "fishing are prohibited throughout the catchment area, which covers nearly "
        "1,800 square kilometres of the Bohemian-Moravian Highlands. The watershed "
        "is managed as a closed zone with controlled farming and no heavy industry "
        "permitted. This isolation has allowed the Želivka valley to remain one of "
        "the least disturbed river corridors in central Bohemia, supporting thriving "
        "populations of otters, kingfishers, and various waterfowl despite its "
        "proximity to one of Europe's largest capital cities."
    ),
    "Slezska Harta": (
        "Slezská Harta is the largest reservoir in Moravian Silesia and one of the "
        "youngest major dams in the Czech Republic, completed in 1997 on the Moravice "
        "River. The rockfill dam stands 65 metres tall and holds 209 million cubic "
        "metres, serving primarily as a water supply reservoir for the Opava and "
        "Ostrava agglomerations as well as providing flood protection for the Opava "
        "valley downstream. The reservoir fills a broad valley in the Jeseník foothills, "
        "surrounded by the forested ridges of the Hrubý Jeseník mountains. Its "
        "construction required the relocation of seven villages and more than 2,000 "
        "inhabitants — one of the largest resettlements in Czech post-war history. "
        "The former village sites are visible during low-water periods, a haunting "
        "reminder of the communities that once thrived in this valley. Since completion, "
        "the reservoir has developed into a regional leisure destination, with sailing, "
        "windsurfing, and cycling paths along its shoreline."
    ),
    "Nove Mlyny": (
        "Nové Mlýny is a system of three connected reservoirs on the lower Dyje "
        "River in South Moravia, completed between 1978 and 1989. The earthfill "
        "dam complex holds a combined 142 million cubic metres and covers over "
        "30 square kilometres, making it the largest reservoir in Moravia by surface "
        "area. The reservoirs were built primarily for flood protection, irrigation "
        "of the fertile South Moravian agricultural plains, and recreation. However, "
        "their construction was highly controversial: the flooding of the Dyje floodplain "
        "destroyed one of the most biodiverse wetland ecosystems in Central Europe "
        "and submerged the historic Mušov village along with significant archaeological "
        "sites. Today the reservoirs support thriving populations of waterbirds "
        "including the largest nesting colony of great cormorants in the Czech Republic. "
        "The middle reservoir is designated a Ramsar wetland site, acknowledging "
        "its importance as a substitute habitat for migratory birds despite the "
        "ecological damage caused by its construction."
    ),
    "Vranov": (
        "Vranov is one of the oldest major reservoirs in the Czech Republic, completed "
        "in 1934 on the Dyje River in the picturesque Podyjí valley near the "
        "Austrian border. The concrete gravity dam stands 47 metres tall and holds "
        "133 million cubic metres. Built during the interwar period of the First "
        "Czechoslovak Republic, Vranov was a remarkable engineering achievement of "
        "its era and served the dual purpose of hydroelectric generation and "
        "recreational development. The reservoir sits within the Podyjí National Park, "
        "a UNESCO biosphere reserve protecting the deeply incised meanders of the "
        "Dyje valley — one of the most biodiverse landscapes in Central Europe. "
        "The rugged canyon walls and oak-hornbeam forests surrounding the reservoir "
        "create a landscape of extraordinary natural beauty. Vranov town and its "
        "Baroque castle, perched dramatically above the dam wall, are among the "
        "most photographed sights in South Moravia."
    ),
    "Dalesice": (
        "Dalešice Reservoir on the Jihlava River in the Vysočina Region was completed "
        "in 1978 primarily to serve as a cooling water source and compensating basin "
        "for the Dukovany Nuclear Power Plant — the only nuclear facility in the "
        "Czech Republic. The rockfill dam stands 100 metres tall and holds 127 million "
        "cubic metres. The reservoir works in tandem with the adjacent Mohelno "
        "Reservoir, forming a closed cooling cycle that supplies the power plant with "
        "a reliable water source independent of fluctuations in the Jihlava River. "
        "Beyond its industrial role, Dalešice also provides hydroelectric generation "
        "and serves as a valuable recreational area. The steep dam and its deep "
        "reservoir occupy a narrow valley carved through the metamorphic rocks of "
        "the Bohemian Massif, with forested slopes reaching down to the water's edge. "
        "The dam's height-to-capacity ratio makes it one of the most impressive "
        "engineering structures in Moravia."
    ),
    "Prisecnice": (
        "Přísečnice Reservoir in the Ore Mountains of northwestern Bohemia was "
        "completed in 1976 on the Přísečnice stream, a small tributary of the Ohře. "
        "The rockfill dam stands 61 metres tall and holds 50 million cubic metres, "
        "serving primarily as a drinking water supply for the industrial towns of "
        "the Chomutov district. The construction was extraordinarily controversial: "
        "the entire town of Přísečnice, including its historic church and cemetery, "
        "was demolished and flooded to make way for the reservoir. The 460-year-old "
        "town was one of the largest communities ever deliberately submerged in Czech "
        "history, and the forced resettlement of its population remains a sensitive "
        "subject. During severe droughts or exceptional drawdowns, the ruins of "
        "the church tower and building foundations re-emerge above the waterline, "
        "drawing visitors who come to see the ghostly remains of the lost town. "
        "The reservoir sits in a landscape shaped by centuries of silver mining "
        "and later open-cast coal extraction."
    ),
    "Kruzberk": (
        "Kružberk Reservoir on the upper Moravice River in Moravian Silesia was "
        "completed in 1955, making it one of the oldest operational reservoirs in "
        "the region. The concrete gravity dam stands 35 metres tall and holds "
        "35 million cubic metres. Its primary function is drinking water supply "
        "for Opava and the surrounding districts. The reservoir forms the upstream "
        "component of the Kružberk-Slezská Harta system, where it captures the "
        "clear waters of the upper Moravice before they descend to the larger "
        "downstream reservoir. The surrounding landscape is characterised by the "
        "rolling hills of the Nízký Jeseník range, with spruce forests covering "
        "the catchment and providing natural filtration for the water supply. "
        "The dam site was chosen for the geological stability of the underlying "
        "amphibolite bedrock, which proved ideal for the gravity dam construction "
        "technique used at the time. Kružberk remains a vital component of the "
        "Opava region's water security infrastructure."
    ),
    "Josefuv Dul": (
        "Josefův Důl Reservoir on the Kamenice River in the Jizerské hory Mountains "
        "of northern Bohemia was completed in 1982, primarily to supply drinking water "
        "to the cities of Liberec and Jablonec nad Nisou. The rockfill dam stands "
        "44 metres tall and holds 24 million cubic metres. The reservoir occupies "
        "a densely forested valley in the Jizerské hory Protected Landscape Area — "
        "a region renowned for its extensive spruce forests, peat bogs, and high "
        "annual rainfall, making it one of the wettest landscapes in the Czech Republic. "
        "The catchment receives over 1,200 millimetres of precipitation per year, "
        "ensuring reliable water yields even in dry summers. The reservoir played "
        "a significant role during the acid rain crisis of the 1970s and 1980s, "
        "when widespread forest dieback threatened to degrade water quality. "
        "Today, following extensive forest regeneration and liming of acidified "
        "soils, the watershed is recovering and water quality at Josefův Důl "
        "meets the highest European standards."
    ),
    "Flaje": (
        "Fláje Reservoir sits high in the Ore Mountains of northwestern Bohemia "
        "on the Flájský potok stream, near the border with Germany. The concrete "
        "gravity dam was completed in 1963 and stands 59 metres tall, holding "
        "23 million cubic metres. It serves as a drinking water source for "
        "communities in the Most and Teplice districts. The reservoir occupies "
        "one of the highest positions of any large dam in the Czech Republic, "
        "with its water surface at approximately 700 metres above sea level. "
        "The surrounding landscape of the Ore Mountains carries deep industrial "
        "heritage from centuries of silver, tin, and uranium mining, as well as "
        "more recent open-cast lignite extraction in the valleys below. The "
        "high-altitude location means the reservoir is often snow-covered in "
        "winter, and its catchment is subject to frequent fog and low cloud. "
        "The area has seen significant reforestation since the acid rain damage "
        "of the communist era, with mixed forests gradually replacing the lost "
        "spruce monocultures."
    ),
    "Stanovice": (
        "Stanovice Reservoir on the Teplá River near the famous spa town of "
        "Karlovy Vary was completed in 1978. The concrete gravity dam stands "
        "55 metres tall and holds 21 million cubic metres, providing drinking "
        "water supply for Karlovy Vary and surrounding districts. The Teplá River "
        "originates in the forested hills of the Slavkov Forest Protected Landscape "
        "Area and carries waters of exceptionally high purity before reaching the "
        "reservoir. The proximity to Karlovy Vary — one of the most visited spa "
        "and tourism destinations in Central Europe — gives the reservoir both "
        "strategic importance and scenic significance. The surrounding countryside "
        "of beech forests and meadows provides a peaceful setting for hiking and "
        "cycling. Water quality monitoring at Stanovice is particularly stringent "
        "given the spa town's dependency on clean water for both municipal supply "
        "and the therapeutic mineral springs that have made Karlovy Vary internationally "
        "renowned since the 14th century."
    ),
    "Zermanice": (
        "Žermanice Reservoir on the Lučina River in the Silesian Beskids foothills "
        "is the primary water supply reservoir for the industrial city of Ostrava "
        "and surrounding municipalities. The earthfill dam was completed in 1957 "
        "and stands 32 metres tall, holding 25 million cubic metres. Located in "
        "the southeastern corner of the Czech Republic near the Slovak and Polish "
        "borders, the reservoir draws water from the Beskids mountains, where the "
        "Lučina and its tributaries collect rainfall from forested catchments. "
        "The reservoir's importance is amplified by the scale of the Ostrava "
        "agglomeration — one of the largest urban-industrial concentrations in "
        "Central Europe — which demands a reliable and high-capacity water supply "
        "for its population and heavy industries. The reservoir is supplemented "
        "by water transfers from the larger Šance Reservoir on the Ostravice River "
        "during dry periods. The surrounding Beskydy Protected Landscape Area offers "
        "recreational opportunities within easy reach of the industrial city."
    ),
}


def get_cz_dam_description(name_en: str) -> str:
    """Return the prose description for a Czech dam, or a generic fallback."""
    return CZ_DAM_DESCRIPTIONS.get(
        name_en,
        (
            f"{name_en} is one of the Czech Republic's significant water reservoirs, "
            "managed by the CHMI (Czech Hydrometeorological Institute). It plays an "
            "important role in regional water supply, flood protection, and hydroelectric "
            "generation in the Czech river system."
        ),
    )
