"""
Unique prose descriptions for each of the 17 major Cyprus dams.
Used on dam detail pages to provide SEO-friendly, human-readable context.
"""
from __future__ import annotations

DAM_DESCRIPTIONS: dict[str, str] = {
    "Kouris": (
        "Kouris is the largest dam in Cyprus, located in the Limassol district on the Kouris River. "
        "Completed in 1988 after several years of construction, its 115 MCM capacity makes it the undisputed "
        "backbone of the island's water supply infrastructure. The earth-fill dam stands 110 metres tall amid "
        "the Troodos foothills, a commanding structure that took on an outsized importance almost immediately "
        "after it filled for the first time. The greater Limassol area — Cyprus's second-largest city and a "
        "major tourist hub — depends heavily on Kouris for its drinking water, and the dam also feeds the "
        "Southern Conveyor Project, the trans-island pipeline that redistributes water from the wetter west "
        "to the drier east. The Kouris River catchment spans the southern slopes of the Troodos massif, "
        "capturing rainfall from elevations above 1,500 metres where winter snowpack and orographic "
        "precipitation are most reliable. This gives Kouris a larger and more dependable hydrological "
        "regime than most other Cypriot reservoirs. During the severe drought of the early 2000s, Kouris "
        "dropped to critically low levels — below 5% capacity — prompting emergency desalination contracts "
        "and accelerated investment in water recycling. That crisis permanently changed how the Water "
        "Development Department managed the reservoir, introducing more conservative drawdown policies "
        "and stricter demand-side controls. In wetter years, such as 2018-2019, Kouris has overflowed "
        "its spillway — a sight that briefly makes national news and reassures a population acutely "
        "aware of water scarcity. Its reservoir levels are widely regarded as a barometer for the "
        "island's overall water security. When Kouris is healthy, Cyprus breathes easier; when it "
        "runs low, the pressure on desalination plants and public consumption habits intensifies sharply."
    ),
    "Asprokremmos": (
        "Asprokremmos is the second-largest dam in Cyprus, situated in the Paphos district on the Xeros "
        "River in the foothills of the western Troodos range. Built in 1982 with a capacity of 52 MCM, "
        "the 53-metre earth-fill structure was a major engineering undertaking that transformed water "
        "management across the entire western region of the island. Paphos town and its surrounding "
        "communities — including the rapidly expanding tourist strip along the coast — depend on "
        "Asprokremmos for the bulk of their drinking water supply. Beyond urban needs, the dam feeds "
        "an extensive irrigation network that supports the banana plantations, citrus groves, and "
        "vegetable farms that define the agricultural economy of the Paphos lowlands. The Xeros River "
        "catchment receives rainfall from the higher western Troodos slopes, but the region is "
        "noticeably drier than the central massif, making Asprokremmos more vulnerable to extended "
        "dry spells than its counterpart at Kouris. During the prolonged droughts of the late 1990s "
        "and early 2000s, Asprokremmos declined dramatically, prompting emergency water transfers via "
        "the Western Conveyor and accelerating the push for desalination capacity on the western coast. "
        "The reservoir has also played a role in flood attenuation — the Xeros valley is prone to "
        "flash flooding in heavy rain years, and the dam's presence moderates downstream peak flows. "
        "Asprokremmos is a key indicator of drought severity in the Paphos catchment area, and its "
        "level is monitored closely by agricultural water users who depend on seasonal allocations. "
        "The reservoir's shores attract birdwatchers, particularly during migration periods when "
        "waders and waterfowl gather on the exposed mudflats during low-water years, adding an "
        "unexpected ecological dimension to this critical piece of infrastructure."
    ),
    "Evretou": (
        "Evretou dam is located in the Paphos district on the Stavros tis Psokas River, a tributary "
        "system draining the rugged western Troodos. Completed in 1986 with a capacity of 24 MCM, the "
        "72-metre earth-fill dam is nestled in a steep valley surrounded by dense pine and cedar forest, "
        "much of it within the Paphos Forest — one of the largest state forests in Cyprus. This setting "
        "gives Evretou one of the most dramatic and scenically rewarding approaches of any dam on the "
        "island. The Chrysochou valley downstream is among the most productive agricultural areas in "
        "western Cyprus, producing table grapes, avocados, and a wide variety of citrus fruits, all of "
        "which depend significantly on irrigation water drawn from the Evretou system. The dam also "
        "contributes to the water supply of Polis Chrysochous and surrounding coastal communities. "
        "The Stavros tis Psokas catchment receives some of the highest annual rainfall totals on the "
        "island — often exceeding 900 mm in the upper reaches — making Evretou one of the more "
        "resilient reservoirs during moderate drought periods. This higher rainfall is partly driven "
        "by the forest cover itself, which promotes orographic precipitation and slows surface "
        "runoff, giving the catchment an unusually reliable hydrological character. Evretou was "
        "completed during a period of rapid dam construction across Cyprus in the 1980s, as the "
        "government pushed to expand irrigation infrastructure ahead of Cyprus's growing agricultural "
        "export ambitions. Since then, shifts in land use, climate, and export markets have changed "
        "how the reservoir's water is allocated, with drinking water increasingly prioritised over "
        "irrigation during dry years. The dam is accessible by road and draws modest visitor interest "
        "from hikers exploring the Paphos Forest trails nearby."
    ),
    "Kannaviou": (
        "Kannaviou is a modern roller-compacted concrete dam in the Paphos district, completed in 2005 "
        "on the Ezousa River. With a capacity of 17.2 MCM, it is one of the newest major additions to "
        "Cyprus's water storage infrastructure and the only roller-compacted concrete dam in the national "
        "system. The 75-metre structure was designed to complement Asprokremmos, which lies downstream in "
        "the same river system, by capturing water higher in the catchment before it can evaporate or "
        "seep away in the drier lowlands. The Ezousa River drains the central-western Troodos slopes, "
        "a zone that receives moderate to high winter rainfall, particularly during years when Atlantic "
        "frontal systems track across the eastern Mediterranean. Kannaviou supports both drinking water "
        "supply and irrigation for the Paphos lowlands, and it is connected to the broader western "
        "water transfer network that links Paphos district's reservoirs. Its relatively recent "
        "construction means it benefits from modern instrumentation, automated monitoring systems, "
        "and engineering tolerances that older dams on the island predate. The dam was part of a "
        "second wave of Cypriot infrastructure investment that followed the severe droughts of the "
        "late 1990s, a period that exposed significant gaps in storage capacity across the west of "
        "the island. Kannaviou's construction also required the resettlement of a small number of "
        "properties in the valley, a process managed in the early 2000s. Today, the reservoir plays "
        "a growing and increasingly recognised role in the western water network, particularly as "
        "climate variability makes annual rainfall less predictable and the value of every available "
        "storage megalitre rises accordingly."
    ),
    "Arminou": (
        "Arminou dam straddles the border of the Paphos and Limassol districts on the Diarizos River, "
        "one of the most scenic river valleys in the Troodos mountains. Completed in 1998 with a "
        "capacity of 4.3 MCM, the 42-metre dam sits in a steep, narrow gorge carved through ancient "
        "limestone and igneous rock, giving it a dramatic setting that belies its relatively modest "
        "storage volume. Despite its smaller size, Arminou occupies a strategically important position "
        "in the regional water network because its outflow can be directed into the Southern Conveyor "
        "Project — the main pipeline linking western and eastern Cyprus — supplementing supply during "
        "dry periods when larger reservoirs upstream are drawing down. The Diarizos catchment is fed "
        "by some of the highest parts of the Troodos massif, including slopes above 1,800 metres where "
        "winter snowfall is a meaningful contributor to annual runoff. This gives Arminou access to "
        "snowmelt-driven recharge in late winter and early spring, a more reliable seasonal input than "
        "most lower-altitude catchments enjoy. The valley around Arminou is known for its traditional "
        "stone villages, terraced vineyards, and old-growth carob trees, and the reservoir has become "
        "a modest visitor destination, particularly among hikers using the Diarizos nature trails. "
        "The dam was constructed relatively late in Cyprus's dam-building era, part of an effort to "
        "capture remaining viable sites in the Troodos before urban and environmental constraints "
        "made new projects impossible. Arminou's contribution to the Southern Conveyor during "
        "critical summer drawdown periods makes it a small but meaningful piece of the island's "
        "overall water resilience strategy."
    ),
    "Germasoyeia": (
        "Germasoyeia dam is located just north of Limassol city on the Germasoyeia River, making it "
        "the closest major reservoir to a large urban centre in Cyprus. Built in 1968 with a capacity "
        "of 13.5 MCM and standing 48 metres tall, it was among the first modern dams constructed on "
        "the island as Cyprus began investing seriously in water infrastructure following independence. "
        "Its proximity to Limassol — one of Cyprus's most densely populated and economically active "
        "cities — gave it immediate strategic importance for municipal water supply. The Germasoyeia "
        "River drains the southern slopes of the Troodos massif, a catchment that benefits from "
        "moderate winter rainfall but is susceptible to prolonged dry spells, particularly in years "
        "when the island's typical winter storm track shifts northward. Over the decades, as Limassol's "
        "population and tourist infrastructure expanded dramatically, Germasoyeia alone proved "
        "insufficient to meet demand, necessitating integration with the Southern Conveyor and "
        "increasing reliance on Kouris reservoir upstream. Today, Germasoyeia supplies a portion "
        "of Limassol's drinking water and supports some irrigation in the wider Limassol district, "
        "but it operates within a closely coordinated regional system rather than as an independent "
        "source. The dam's location has made it a cultural fixture — the Germasoyeia river valley "
        "below the dam is a popular walking and cycling destination for Limassol residents, with "
        "cafes and picnic areas lining the riverbanks. During low-water years, the exposed reservoir "
        "bed reveals centuries of sedimentation that offer a visible record of the catchment's "
        "geological history. The reservoir remains one of the most visited dam sites in Cyprus "
        "precisely because of its accessibility from the city."
    ),
    "Kalavasos": (
        "Kalavasos dam lies in the Larnaca district on the Vasilikos River, in a gently rolling "
        "landscape between the Troodos foothills and Cyprus's southern coast. Completed in 1985 with "
        "a capacity of 17.1 MCM and standing 60 metres tall, the earth-fill dam was constructed as "
        "part of the broader expansion of water storage capacity across the south of the island during "
        "the 1980s. The Vasilikos River catchment is one of the more easterly draining systems on the "
        "southern slopes of the Troodos, and its rainfall regime is notably drier than the western "
        "mountain catchments — annual averages in the mid-300s of millimetres are typical, meaning "
        "Kalavasos depends heavily on intense winter storms to replenish its storage. The dam serves "
        "a diverse set of water users: the Vasilikos industrial zone — home to the Vasilikos power "
        "station and cement works — draws significant process water from the reservoir, while local "
        "agriculture also depends on seasonal irrigation allocations. Kalavasos also functions as a "
        "feeder point for the Southern Conveyor Project, supplementing water deliveries to the drier "
        "Larnaca and Famagusta districts further east. The area around the dam is archaeologically "
        "rich: the Neolithic settlement of Kalavasos-Tenta, one of Cyprus's most significant "
        "prehistoric sites, lies within a few kilometres, and the region has yielded substantial "
        "evidence of Bronze Age copper smelting. During droughts, the retreating reservoir occasionally "
        "exposes sediment layers that contain archaeological material, drawing attention from the "
        "Department of Antiquities. The dam itself is accessible via a scenic road that passes "
        "through vineyards and carob orchards characteristic of this transitional zone between "
        "the mountains and the coast."
    ),
    "Lefkara": (
        "Lefkara dam is situated in the Larnaca district on the Pentaschoinos River, in a striking "
        "limestone landscape near the village of Lefkara — famous throughout Cyprus and internationally "
        "for its intricate handmade lace, Lefkaritika. Built in 1981 with a capacity of 13.9 MCM and "
        "standing 68 metres tall, the earth-fill dam was an important early investment in water "
        "infrastructure for the Larnaca district, a region that receives relatively modest rainfall "
        "and has historically been water-stressed. The Pentaschoinos River drains the eastern Troodos "
        "rain shadow zone — a region where annual precipitation is significantly reduced compared to "
        "the windward western slopes, typically averaging 400-500 mm in the upper catchment and "
        "declining sharply toward the coast. This semi-arid character means Lefkara's reservoir "
        "levels closely track winter storm intensity and frequency, and the dam can shift from "
        "comfortably full to critically low within a single dry year. The reservoir provides "
        "irrigation water for the surrounding agricultural land, particularly the vineyards and "
        "olive groves that are central to the local economy, and it contributes to the regional "
        "water supply network alongside the neighbouring Dipotamos dam upstream. Lefkara sits "
        "within a landscape of white chalk hills and eroded limestone gullies that give the area "
        "a distinctive, almost lunar appearance — a geology that also underlies the poor water "
        "retention characteristics of the catchment soils. The combination of low rainfall, fast "
        "runoff, and limited groundwater recharge makes Lefkara a sensitive indicator of drought "
        "conditions in the eastern Troodos zone, and water managers watch it closely whenever "
        "winter rainfall falls significantly below seasonal averages."
    ),
    "Dipotamos": (
        "Dipotamos dam is located in the Larnaca district on the Pentaschoinos River, upstream of "
        "Lefkara dam in the same catchment system. Completed in 1986 with a capacity of 15.5 MCM "
        "and standing 60 metres tall, the earth-fill structure was built to work in tandem with "
        "Lefkara, giving the Water Development Department greater flexibility in managing the "
        "Pentaschoinos catchment across the full range of rainfall conditions from wet to dry years. "
        "The Pentaschoinos system is one of the more important river catchments in the south-eastern "
        "Troodos, and having two reservoirs operating in series on the same river allows operators "
        "to stage storage — filling Dipotamos first during heavy rainfall, then releasing water "
        "progressively to Lefkara as needed, reducing the risk of spillage losses. The dam sits "
        "in a remote valley of the eastern Troodos foothills, an area that sees little tourist "
        "traffic but is valued for its quiet rural character, traditional stone terracing, and "
        "scattered almond and olive groves. Dipotamos primarily supports agricultural irrigation "
        "in the surrounding region, with a smaller contribution to drinking water supply compared "
        "to its downstream partner. The combined capacity of Dipotamos and Lefkara — just under "
        "30 MCM — makes the Pentaschoinos system a meaningful contributor to Larnaca district's "
        "water budget, particularly given the district's limited rainfall and the absence of "
        "the large-capacity reservoirs that anchor supply in the Limassol and Paphos districts. "
        "Dipotamos also acts as a buffer during heavy winter rainfall events, absorbing peak "
        "flows that would otherwise overwhelm downstream channels and potentially cause "
        "flash flooding in the lower Pentaschoinos valley."
    ),
    "Achna": (
        "Achna dam is located in the Famagusta district, close to the south-eastern coast of "
        "Cyprus in a flat agricultural landscape defined by the famous red soils of the "
        "Kokkinochoria region. Unlike most Cypriot dams that impound river water captured from "
        "rainfall, Achna functions primarily as a storage reservoir for treated wastewater and "
        "desalinated water, with a capacity of 6.8 MCM. Built in 1987, the 15-metre earth-fill "
        "structure is deliberately low-profile, suited to the flat topography of the coastal plain "
        "rather than the steep river gorges where most of Cyprus's conventional dams are sited. "
        "The Kokkinochoria region — whose name means 'red villages' — is one of Cyprus's most "
        "intensively cultivated agricultural zones, producing potatoes, strawberries, and early "
        "vegetables for export to European markets. This intensive agriculture demands substantial "
        "irrigation water in a region that receives less than 350 mm of annual rainfall and has "
        "no significant river systems. Achna's role in wastewater reuse makes it an increasingly "
        "important asset as Cyprus moves toward closing the water cycle and reducing dependence "
        "on rainfall-dependent storage. The treated water stored at Achna is primarily used for "
        "agricultural irrigation, freeing up higher-quality fresh water for domestic consumption. "
        "As climate projections for the eastern Mediterranean consistently point toward drier "
        "winters and hotter summers, the Achna model of non-conventional water use is gaining "
        "recognition as a template for managing water scarcity in low-rainfall regions. The "
        "reservoir also provides incidental wetland habitat in an otherwise dry and intensively "
        "farmed landscape, attracting migratory birds and supporting a modest but notable "
        "local biodiversity value."
    ),
    "Polemidia": (
        "Polemidia dam lies on the outskirts of Limassol on the Garyllis River, making it one of "
        "the most centrally located reservoirs in Cyprus's urban landscape. Completed in 1965 with "
        "a capacity of 3.4 MCM and standing 35 metres tall, it is among the oldest modern dams on "
        "the island — constructed in the early years after Cyprus's independence when the nascent "
        "republic was beginning to build national water infrastructure. In its original function, "
        "Polemidia supplied drinking water directly to Limassol, at that time a much smaller city "
        "than it is today. As Limassol's population grew through the 1970s and 1980s, particularly "
        "following the economic disruptions of the 1974 war, the city's demand quickly outpaced "
        "what Polemidia could provide, and the dam's role gradually shifted toward irrigation support "
        "while larger reservoirs — Kouris and Germasoyeia — took over municipal supply. The Garyllis "
        "River catchment is modest in extent, draining the lower southern Troodos slopes within "
        "a relatively compact area, which limits Polemidia's ability to capture significant runoff "
        "volumes during winter storms. Today, the surrounding area has become increasingly urbanised "
        "as Limassol expands outward, and the reservoir now serves as a green corridor within the "
        "metropolitan fringe — a rare open water surface and informal nature area amid the expanding "
        "built environment. The dam attracts local walkers and cyclists, and environmental groups "
        "have occasionally highlighted its value as urban green infrastructure. Polemidia's "
        "longevity as a functioning reservoir — over six decades — reflects the durability of "
        "mid-twentieth century Cypriot civil engineering and the ongoing relevance of smaller "
        "reservoirs even as the island has built far larger storage capacity."
    ),
    "Mavrokolympos": (
        "Mavrokolympos dam is situated in the Paphos district near the village of Kissonerga, "
        "close to the western coast and within easy reach of Paphos town. Completed in 1966 with "
        "a capacity of 2.1 MCM and standing 30 metres tall, it is one of the smaller dams in the "
        "national network, built in the same era as Polemidia as part of Cyprus's first generation "
        "of post-independence water infrastructure. The earth-fill structure captures seasonal "
        "runoff from the western foothills of the Troodos range — a drier zone compared to the "
        "higher central catchments — and channels it toward supporting the agricultural needs of "
        "the coastal Paphos lowlands. The area downstream of Mavrokolympos is notable for its "
        "banana plantations and citrus groves, crops that require consistent irrigation throughout "
        "the dry Mediterranean summer and benefit from reliable water allocation from the reservoir. "
        "The western Paphos coast, where Mavrokolympos sits, receives less orographic precipitation "
        "than the eastern-facing Troodos slopes, meaning the dam's catchment is more exposed to "
        "the high rainfall variability that characterises the drier western coastal strip. In "
        "particularly wet winters — such as those following strong La Niña events in the "
        "Mediterranean — Mavrokolympos fills rapidly and can spill; in droughts, it may drain "
        "to near-empty within a single dry season. Despite its modest size, the dam is a useful "
        "indicator of rainfall patterns in the drier western catchments and complements the "
        "much larger Asprokremmos reservoir that dominates Paphos district's water budget. "
        "The coastal setting gives the reservoir an unusually mild microclimate, with evaporation "
        "losses somewhat higher than at higher-altitude Troodos reservoirs."
    ),
    "Argaka": (
        "Argaka dam is located in the Paphos district on the northern slopes of the Troodos "
        "mountains, near the village of Argaka on the shores of Chrysochou Bay. Built in 1964 "
        "with a capacity of 0.99 MCM, it is one of the smallest dams in the national network "
        "and one of the earliest constructed after Cyprus's independence in 1960. The compact "
        "earth-fill structure captures seasonal runoff from the north-facing lower Troodos slopes "
        "— a catchment that receives rainfall from both westerly Atlantic fronts tracking across "
        "the Mediterranean and occasional northerly air masses from the Anatolian plateau, giving "
        "it a slightly different seasonal rainfall pattern than the more southerly Troodos catchments. "
        "Argaka primarily supports local citrus and olive cultivation in the Chrysochou valley, "
        "an area long associated with high-quality agricultural produce. The Chrysochou Bay "
        "region is one of the quieter and less developed parts of the island, and the dam sits "
        "within a landscape of characteristic Mediterranean maquis shrubland and scattered "
        "small-scale terraced agriculture. Argaka's small catchment means it responds very "
        "quickly to rainfall — filling within days of significant winter storms — but also "
        "dries out faster than larger reservoirs during extended dry spells, making it a "
        "sensitive real-time indicator of short-term rainfall events in the north Paphos "
        "district. The dam predates modern water management systems and continues to operate "
        "as a local community-scale asset rather than as part of the larger inter-district "
        "transfer network. Its longevity over more than sixty years of operation reflects "
        "the durability of the original earth-fill engineering and the ongoing local "
        "importance of even small water storage assets in Cyprus's rain-limited landscape."
    ),
    "Pomos": (
        "Pomos dam sits on the north-western coast of Cyprus in the Paphos district, near the "
        "traditional fishing village of Pomos — one of the most remote and least developed "
        "stretches of the Cyprus coastline. Completed in 1967 with a capacity of 0.86 MCM, "
        "it is among the smallest reservoirs in the national system, built in the same first "
        "generation of post-independence infrastructure investment that produced Argaka and "
        "Polemidia in the same period. The earth-fill dam captures runoff from the steep "
        "north-facing Troodos slopes above the coast, a zone where the terrain drops sharply "
        "from forested mountain ridges to a narrow coastal strip with virtually no flat land "
        "between. This dramatic topography concentrates runoff rapidly after rainfall events, "
        "sending short but intense pulses of water down the steep stream channels into the "
        "reservoir. The north-western coastal strip around Pomos receives a distinctive "
        "rainfall pattern: exposed to northerly and north-westerly winds in winter, the "
        "area catches frontal rainfall that other parts of the Paphos district in the rain "
        "shadow of the main Troodos ridge may miss. Pomos supports local agriculture along "
        "the narrow coastal strip, including the small-scale citrus, grape, and olive "
        "cultivation that characterises the village economies of this remote region. "
        "The ecological surroundings of the dam have gained recognition in recent years: "
        "the coastline near Pomos is one of the last undeveloped stretches of the northern "
        "Paphos coast, and the combination of forested slopes, rocky shoreline, and the "
        "reservoir's freshwater habitat supports a locally diverse fauna. The area around "
        "Pomos remains one of the most authentic rural landscapes in Cyprus, little changed "
        "from the pre-tourism era."
    ),
    "Vyzakia": (
        "Vyzakia dam is located in the Nicosia district on the Serrachis River, in the broad "
        "flat expanse of the Morphou plain that stretches across the north-western lowlands of "
        "Cyprus. Built in 1984 with a capacity of 1.7 MCM and standing 22 metres tall, the "
        "earth-fill structure occupies a very different landscape from the mountain dams of "
        "the Troodos — here the terrain is flat and fertile, dominated by the citrus groves "
        "that made the Morphou region one of the most productive agricultural areas in Cyprus "
        "before the island's partition in 1974. The Serrachis River originates in the northern "
        "foothills of the Troodos massif and crosses the Mesaoria plain before discharging "
        "toward Morphou Bay. Its catchment sits in the transition zone between the wetter "
        "mountain slopes and the drier lowland plain, receiving annual rainfall that typically "
        "averages 350-450 mm in the upper reaches but declines sharply downstream. Vyzakia "
        "primarily serves agricultural irrigation, supporting the citrus-growing communities "
        "west of Nicosia that have maintained fruit cultivation in the area despite significant "
        "water stress in dry years. The dam's small capacity relative to the agricultural "
        "demand it serves means it must be managed carefully, with allocations closely "
        "calibrated to seasonal rainfall and recharge rates. Because Vyzakia fills and "
        "drains relatively quickly, it functions as a sensitive indicator of seasonal "
        "rainfall patterns in the Mesaoria plain catchment — rising rapidly after winter "
        "storms and declining steadily through the long dry spring and summer. The flat "
        "surrounding landscape means the reservoir spreads laterally at high levels, "
        "maximising surface area and unfortunately also maximising evaporative losses "
        "during the hot Cypriot summer."
    ),
    "Xyliatos": (
        "Xyliatos dam is located in the Nicosia district in the heart of the Troodos mountains, "
        "near the village of Xyliatos at an elevation that places it well within the forested "
        "mountain zone. Completed in 1982 with a capacity of 1.4 MCM and standing 21 metres "
        "tall, the earth-fill dam captures runoff from the northern Troodos slopes — a "
        "catchment characterised by dense state forest, rocky terrain, and reliable winter "
        "snowfall at the higher elevations. This forested catchment gives Xyliatos a relatively "
        "stable hydrological character: the tree cover intercepts rainfall, slows surface "
        "runoff, and promotes groundwater recharge, smoothing the flow of water into the "
        "reservoir compared to bare or agricultural catchments. The surrounding pine and "
        "golden oak forest belongs to the Troodos State Forest, one of the largest protected "
        "forest areas in Cyprus, which limits agricultural encroachment and helps maintain "
        "the catchment's ecological integrity. Xyliatos primarily supports local agricultural "
        "irrigation in the foothill villages below the reservoir, including the small-scale "
        "viticulture and vegetable growing that characterise mountain communities. The "
        "reservoir and its surrounding forest have become an established destination for "
        "hikers and nature walkers from Nicosia, offering accessible mountain scenery "
        "less than an hour's drive from the capital. A marked nature trail circumnavigates "
        "the reservoir, passing through mature pine woodland and offering views across the "
        "Xyliatos valley. The dam is modest in scale but its mountain setting and forest "
        "environment give it a character quite different from the lowland reservoirs of the "
        "Mesaoria plain or the coastal dams of the Paphos district, contributing to the "
        "landscape value of this popular recreational zone."
    ),
    "Kalopanagiotis": (
        "Kalopanagiotis dam is nestled in the Nicosia district in the Marathasa valley, one of "
        "the most picturesque and historically layered areas of the Troodos mountains. Built "
        "in 1967 with a capacity of 0.36 MCM, it is the smallest dam in the national network "
        "by storage volume, yet it occupies a setting of remarkable cultural and natural "
        "richness. The compact earth-fill structure captures water from the Setrachos River — "
        "a fast-moving mountain stream fed by snowmelt and rainfall from the upper Marathasa "
        "slopes — and directs it toward supporting the cherry and walnut orchards that the "
        "Marathasa valley has been famous for across centuries. Cherry season in Marathasa "
        "is a celebrated annual event that draws visitors from across the island, and the "
        "small-scale irrigation supported by Kalopanagiotis is integral to maintaining "
        "these orchards through the dry early summer months when the cherries ripen. "
        "The Marathasa valley sits within the Troodos UNESCO World Heritage buffer zone, "
        "recognised for its remarkable collection of Byzantine painted churches — including "
        "those of Agios Ioannis Lampadistis monastery directly beside the dam — giving "
        "Kalopanagiotis a cultural significance entirely disproportionate to its physical "
        "scale. The upper Setrachos catchment receives some of the highest snowfall on "
        "the island, and the dam benefits from snowmelt-driven recharge in late winter "
        "and early spring, providing a reliable seasonal pulse of water that agricultural "
        "users in the valley have depended on for generations. Despite its tiny capacity, "
        "Kalopanagiotis holds genuine historical weight as part of the water heritage of "
        "this UNESCO-listed mountain region, where managing scarce water resources "
        "through community infrastructure has been a defining feature of village life "
        "for many centuries."
    ),
}


def get_dam_description(name_en: str) -> str:
    """Return the prose description for a dam, or empty string if not found."""
    return DAM_DESCRIPTIONS.get(name_en, "")
