"""
Unique prose descriptions for Germany's 15 major reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.
"""
from __future__ import annotations

DE_DAM_DESCRIPTIONS: dict[str, str] = {
    "Bleiloch": (
        "The Bleilochtalsperre is Germany's largest reservoir by volume, holding "
        "approximately 215 million cubic metres of water when full. Completed in 1936, "
        "it stretches for 29 kilometres along the Saale River in the Thuringian Slate "
        "Mountains between Saalfeld and Schleiz. The dam itself is a concrete gravity "
        "structure 63 metres tall, impounding the upper Saale catchment which covers "
        "roughly 2,000 square kilometres of forested upland. Together with the adjacent "
        "Hohenwarte reservoir immediately downstream, Bleiloch forms part of the Saale "
        "cascade — a chain of four reservoirs operated by Vattenfall and later by "
        "STEAG and various municipal utilities for hydroelectric power generation. "
        "The reservoir provides significant peak-load electricity capacity and helps "
        "regulate downstream water flow through Gera and Halle. Surrounded by the "
        "rugged cliffs and steep forests of the Saaleland, Bleilochtalsperre has "
        "become a popular recreational destination, with sailing, camping, and hiking "
        "along its deeply indented shoreline. The water quality is classified as "
        "mesotrophic and the reservoir occasionally experiences summer algal blooms "
        "during periods of low flow. In drought years such as 2018 and 2022, "
        "significant historical artefacts from submerged villages were exposed as "
        "water levels dropped to record lows, drawing widespread media attention. "
        "The dam plays a critical role in the broader Saale-Elbe water management "
        "network, particularly during dry summers when downstream navigation and "
        "industrial cooling water demand are high."
    ),
    "Edersee": (
        "The Edertalsperre, known simply as the Edersee, is one of Germany's most "
        "iconic reservoirs and the second largest by volume at 199.3 million cubic "
        "metres. Completed in 1914 for flood control, low-water augmentation of the "
        "Weser and Fulda rivers, and hydroelectric generation, the dam spans the "
        "Eder valley in the northern Hesse highlands near the historic Kellerwald "
        "forest — now a UNESCO-listed national park. The concrete masonry arch dam "
        "stands 48 metres tall and holds back a reservoir that winds for 27 kilometres "
        "through heavily wooded valleys. The Edersee gained international infamy during "
        "the Second World War when the RAF's 617 Squadron, the famous 'Dambusters', "
        "breached it on 16 May 1943 using Barnes Wallis's bouncing bomb, releasing a "
        "devastating flood wave that killed more than 1,200 people downstream. The dam "
        "was rebuilt within months. Today the Edersee is Hesse's most visited tourist "
        "attraction, with boat trips, the historic Burg Waldeck castle overlooking "
        "the southern shore, and a viaduct at Bringhausen that disappears underwater "
        "during high fill periods and re-emerges dramatically as summer droughts lower "
        "the level. The reservoir is managed by the Wasser- und Schifffahrtsamt "
        "Hann. Münden and regulated to support year-round navigation on the Weser."
    ),
    "Hohenwarte": (
        "The Hohenwarte-Talsperre is the second dam in the Saale cascade, built "
        "directly downstream of the Bleilochtalsperre, with a stored volume of "
        "182 million cubic metres. Construction was completed in 1942, making it "
        "roughly contemporaneous with its upstream neighbour. The concrete gravity "
        "dam stands 75 metres above the valley floor, creating a reservoir that "
        "stretches 13 kilometres upstream through the narrow Saale gorge in the "
        "Thuringian Slate Mountains. Hohenwarte operates in close coordination with "
        "Bleiloch: water released from Bleiloch for power generation is captured in "
        "Hohenwarte, and the combined system provides significant pumped-storage "
        "hydroelectric capacity via underground turbines. The reservoir also supplies "
        "process water to the Saalfeld industrial district and recreational water "
        "for lakeside tourism. The steep forested hillsides surrounding the reservoir "
        "are home to breeding populations of black stork and several bat species "
        "that forage over the water surface. During the GDR era the reservoir was "
        "used extensively for water sports and sailing. Today it remains a popular "
        "destination for boating and cycling along the Saaletal Radweg. Like "
        "Bleiloch, Hohenwarte experienced historically low water levels during the "
        "extreme droughts of 2018 and 2019, with inflows falling to less than "
        "40 percent of the long-term average during the summer months."
    ),
    "Bigge": (
        "The Biggetalsperre in North Rhine-Westphalia is the largest reservoir in "
        "the Sauerland region, holding 171.7 million cubic metres when full. Completed "
        "in 1965 by the Ruhrverband, the 49-metre dam impounds the Bigge and Lister "
        "rivers in the hilly Sauerland highlands southeast of Attendorn. The reservoir "
        "was created primarily to secure water supply for the densely populated Ruhr "
        "industrial belt — at the time of construction the largest single water "
        "management project in Germany, displacing three villages and the town of "
        "Alt-Listernohl. Today the Bigge supplies drinking water to roughly 800,000 "
        "people in the Märkisches Sauerland. Adjacent to the main reservoir, the "
        "smaller Listertalsperre acts as a pre-reservoir and quality management buffer. "
        "The Biggesee, as it is locally known, has evolved into one of the most "
        "popular water sports areas in western Germany, with over two million visitors "
        "annually sailing, windsurfing, and kayaking on its 3,000-hectare surface. "
        "Boat excursions and cycle paths around the 60-kilometre shoreline are "
        "major tourist draws. Water quality is strictly protected under the catchment "
        "protection ordinance (Wasserschutzgebietsverordnung) for the Bigge, and "
        "certain shore sections are designated nature reserves for breeding waterbirds. "
        "The Ruhrverband monitors water levels, turbidity, and biological quality "
        "indicators continuously, publishing results on its public data portal."
    ),
    "Mohne": (
        "The Möhnetalsperre is the oldest large reservoir in the Ruhr catchment "
        "and one of Germany's best-known heritage dams. Completed in 1913, the "
        "134.5-million-cubic-metre reservoir in the Soest district of North Rhine-"
        "Westphalia served as the template for a generation of German masonry dam "
        "construction. The 650-metre-long rubble masonry gravity dam, standing "
        "40 metres tall, impounds the Möhne river just above its confluence with "
        "the Ruhr to provide drinking water for the Ruhr industrial region and flood "
        "protection for Soest downstream. Like the Edersee, the Möhne dam was "
        "breached by the Dambusters raid of May 1943 — the breach was repaired "
        "by October of that year. The Möhnesee today is designated a European "
        "bird sanctuary (Vogelschutzgebiet) for wintering waterfowl, particularly "
        "goldeneye, goosander, and tufted duck, which congregate in large numbers "
        "on the reservoir during cold winters. The surrounding Möhnetal nature "
        "park protects extensive riparian habitats. The lakeside resort of Körbecke "
        "on the north shore is a regional recreation centre, and the reservoir is "
        "circumnavigated by a 40-kilometre cycle route. Water supply operations are "
        "managed by the Ruhrverband in coordination with the network of other Ruhr "
        "catchment reservoirs including Sorpe, Verse, and Bigge."
    ),
    "Rappbode": (
        "The Rappbodetalsperre in Saxony-Anhalt's Harz mountains is Germany's tallest "
        "dam at 106 metres and holds 113 million cubic metres — the largest reservoir "
        "in the Harz range. Completed in 1959, the concrete gravity dam impounds the "
        "Rappbode river and its tributary the Warme Bode in the central Harz. The "
        "reservoir is part of a linked system with the upstream Königshütter Talsperre "
        "and the downstream Wendefurth pumped-storage plant, providing both drinking "
        "water supply and peak-load electricity. The Rappbode supplies treated water "
        "to a population of approximately 1.2 million people in the Halle/Saale and "
        "Magdeburg regions, making it one of Germany's most important drinking water "
        "reservoirs. The catchment is protected by a strict buffer zone that restricts "
        "agricultural and forestry activity. Since 2017 the world's longest pedestrian "
        "suspension bridge, the 'Titan RT', has spanned the reservoir valley at the "
        "Rappbode dam, drawing around 300,000 visitors annually to experience the "
        "spectacular 120-metre drop beneath their feet. The Harz reservoir system is "
        "operated by the Talsperrenbetrieb Sachsen-Anhalt. Drought monitoring during "
        "the unprecedented dry years of 2018–2020 showed the Rappbode fell to near- "
        "record lows, prompting emergency water transfer protocols."
    ),
    "Grosse-Dhuenn": (
        "The Große Dhünn-Talsperre in the Bergisches Land region of North Rhine-"
        "Westphalia is Germany's third largest drinking water reservoir by volume, "
        "holding 81 million cubic metres when at full supply level. Completed in 1985, "
        "the zoned earth-fill embankment dam stands 52 metres tall and impounds the "
        "Große Dhünn river in the hills southeast of Wuppertal. The reservoir supplies "
        "drinking water to the Wuppertal, Remscheid, Solingen, and Leverkusen area — "
        "a densely populated industrial corridor of roughly 800,000 people. Water "
        "quality protection is especially stringent: the entire catchment is designated "
        "as a water protection zone (Wasserschutzgebiet) in which synthetic fertiliser "
        "and pesticide application is strictly regulated. The reservoir works in "
        "tandem with the smaller Vorsperre Große Dhünn upstream, which functions as "
        "a settling basin and quality buffer. The Dhünn valley ecosystem is notable "
        "for its populations of fire salamander, kingfisher, and various highland "
        "meadow plant communities. Recreational activities are restricted to protect "
        "water quality, though a cycle path runs along the eastern shoreline. The "
        "reservoir is operated by the Wupperverband, which publishes real-time "
        "fill level data and water quality reports for stakeholders in the region."
    ),
    "Eibenstock": (
        "The Talsperre Eibenstock in the Erzgebirge mountains of Saxony holds "
        "76.4 million cubic metres of water and is the largest reservoir in the "
        "Saxon Water Management system. Completed in 1975, the 63-metre concrete-"
        "faced rockfill dam impounds the Zwickauer Mulde river near the town of "
        "Eibenstock in the Erzgebirge district. The reservoir was constructed "
        "primarily to supply drinking water to the Zwickau, Karl-Marx-Stadt "
        "(now Chemnitz), and Plauen urban areas in the heavily industrialised "
        "Saxon lowlands. During the GDR era it also served as a strategic water "
        "reserve for the textile and metalworking industries in the Erzgebirge "
        "foothill towns. Today the Talsperre Eibenstock is operated by the "
        "Landestalsperrenverwaltung des Freistaates Sachsen (LTV) and forms the "
        "cornerstone of the Zwickau regional water supply grid, which distributes "
        "treated water to more than 600,000 consumers. The surrounding Erzgebirge "
        "landscape is characterised by high moorland plateaus, spruce and beech "
        "forests, and traditional mining heritage. Recreational activities including "
        "hiking and fishing are permitted in designated areas. The reservoir's "
        "exposed upland catchment makes it particularly sensitive to forest "
        "dieback — a significant management challenge given the ongoing bark "
        "beetle epidemic that has affected large parts of the Saxon Erzgebirge."
    ),
    "Sorpe": (
        "The Sorpetalsperre in the Sauerland district of North Rhine-Westphalia "
        "holds 70.4 million cubic metres and was completed in 1935 as part of the "
        "Ruhr catchment expansion programme. The 69-metre earth-fill embankment dam "
        "with a concrete core wall was, at the time of completion, the largest earth "
        "dam in Germany. It was the third target of the famous Dambusters raid in "
        "May 1943, but withstood the bouncing bomb attack because its construction "
        "type — unlike the concrete masonry dams at Möhne and Eder — absorbed the "
        "shock without catastrophic failure. The Sorpe supplies water to the greater "
        "Ennepe-Ruhr district and forms part of the Ruhrverband's integrated reservoir "
        "management network. The surrounding Sorpetal valley is a protected landscape "
        "area and a popular destination for hiking, cycling, and winter cross-country "
        "skiing. The 60-kilometre circumnavigation cycle route around the Sorpesee "
        "is particularly popular with families. Water quality is monitored under "
        "the EU Water Framework Directive as part of the Ruhr catchment plan, and "
        "the reservoir meets current drinking water quality standards. In dry years "
        "the Sorpe can be drawn down significantly as it acts as a strategic "
        "reserve buffer when the larger Bigge reservoir is at low capacity."
    ),
    "Poehl": (
        "The Talsperre Pöhl in the Vogtland district of Saxony holds 64.6 million "
        "cubic metres and is the second largest reservoir managed by the Landes-"
        "talsperrenverwaltung des Freistaates Sachsen. Completed in 1964, the "
        "66-metre concrete-faced rockfill dam impounds the Trieb river in the "
        "rolling forested hills between Plauen and Zwickau. The reservoir was "
        "constructed during the GDR era to provide drinking water to the Vogtland "
        "textile manufacturing towns and to augment low-flow conditions in the Trieb "
        "and lower White Elster river. Today it supplies approximately 300,000 "
        "people across the Plauen urban area and adjacent rural districts. "
        "The Talsperre Pöhl has developed into a major recreation hub for the "
        "Vogtland region, with extensive sailing and windsurfing infrastructure, "
        "camping sites, and a beach area at Rümpf popular during summer months. "
        "The LTV operates a visitor information centre and guided tours of the "
        "dam structure during the summer season. Water quality monitoring regularly "
        "shows mesotrophic conditions with seasonal cyanobacterial blooms requiring "
        "management by aeration and phosphorus binding treatments. The catchment "
        "has experienced significant spruce forest dieback since 2018 due to the "
        "combination of drought stress and bark beetle infestation, raising concerns "
        "about sediment runoff and long-term water quality impacts."
    ),
    "Kriebstein": (
        "The Talsperre Kriebstein on the Zwickauer Mulde river in the Mittelsachsen "
        "district of Saxony was completed in 1930, making it one of Germany's "
        "oldest large reservoirs still in active service. With a capacity of "
        "33.6 million cubic metres, the concrete gravity dam stands 37 metres "
        "tall and impounds a valley that had been the site of the historic "
        "Kriebstein castle since the 14th century. The castle, perched dramatically "
        "above the reservoir on a rocky promontory, is now one of Saxony's most "
        "visited medieval monuments and can be reached by boat from the Kriebstein "
        "harbour. The reservoir was originally built for flood control and "
        "hydroelectric power generation serving the Döbeln and Chemnitz area. "
        "Today it is managed by the LTV Sachsen primarily for flood protection, "
        "recreation, and as a compensation reservoir for downstream ecological flow "
        "requirements under the EU Water Framework Directive. The surrounding "
        "Zwickauer-Mulde-Tal nature park preserves significant riparian habitats "
        "with otter, kingfisher, and breeding populations of sand martin in the "
        "steep clay banks. The Kriebstein reservoir is a popular sailing and "
        "rowing destination, and the dam structure is open to guided visits."
    ),
    "Verse": (
        "The Versetalsperre in the Märkisches Sauerland of North Rhine-Westphalia "
        "holds 32.8 million cubic metres of water within the Ruhrverband's integrated "
        "reservoir network. Completed in 1952, the 52-metre rockfill dam impounds "
        "the Verse river near Lüdenscheid. The reservoir was built primarily to "
        "augment the water supply of the rapidly expanding metalworking industries "
        "in the Lüdenscheid and Iserlohn area, which required large volumes of "
        "process cooling water in addition to drinking water. Today the Versetal "
        "reservoir supplies the Märkisches Sauerland water grid which covers "
        "approximately 200,000 consumers. It forms part of the Ruhrverband's "
        "integrated reservoir cascade management, with water transfers possible "
        "between Verse, Bigge, and the larger Möhne reservoir during drought "
        "periods. The surrounding Versetal valley is protected as a landscape "
        "conservation area, and the rocky hillsides support populations of "
        "peregrine falcon and raven which nest on the steep rocky outcrops above "
        "the dam. A shoreline footpath offers accessible recreation, and the "
        "Versetal visitor centre provides information about water management in "
        "the Sauerland. Turbidity and microbiological quality indicators are "
        "continuously monitored by the Ruhrverband's environmental laboratory."
    ),
    "Leibis-Lichte": (
        "The Leibis-Lichte-Talsperre in Thuringia is Germany's newest large "
        "reservoir, completed in 2006 after nearly three decades of planning, "
        "construction delays, and political disruption spanning both the GDR "
        "and reunified Germany eras. With a storage capacity of 32.8 million "
        "cubic metres, the 102-metre-tall concrete gravity dam impounds the "
        "Lichte river in the deeply incised slate valleys of the eastern "
        "Thuringian Forest near Stadtilm and Saalfeld. The reservoir was "
        "designed primarily to secure drinking water supply for the Erfurt, "
        "Saalfeld, and Rudolstadt urban areas, supplementing the older Leibis "
        "and Treba reservoirs in the upper Saale system. Construction involved "
        "the challenging relocation of several villages and the rerouting of "
        "the historic Rennsteig highway. The Lichte valley ecosystem, including "
        "habitat for common kingfisher and white-throated dipper, was carefully "
        "assessed and mitigation measures implemented. Today the reservoir is "
        "operated by the Thüringer Fernwasserversorgung and provides drinking "
        "water to approximately 500,000 people in central Thuringia. Its "
        "relatively young age means the water quality is among the cleanest "
        "of any comparable German reservoir, with low nutrient levels and "
        "excellent microbiological standards maintained by the extensive "
        "protected catchment zone."
    ),
    "Agger": (
        "The Aggertalsperre in the Bergisches Land of North Rhine-Westphalia "
        "holds 20.1 million cubic metres and occupies a picturesque valley in "
        "the Agger river upstream of Gummersbach. Completed in 1927, the "
        "57-metre concrete gravity dam was one of the pioneering large reservoir "
        "projects in the Wupper and Agger catchment area, built to supply water "
        "to the growing industrial towns of Gummersbach, Wipperfürth, and the "
        "broader Oberbergisches Land. Today the Aggersee, as the reservoir is "
        "locally known, is managed by the Wupperverband and supplies drinking "
        "water to approximately 150,000 people in the Oberbergisches Land "
        "district. The reservoir also provides recreational amenities including "
        "sailing and pedal boating, and the Aggertal cycle route runs along "
        "its eastern shore connecting Gummersbach to Wipperfürth. A smaller "
        "pre-reservoir, the Vorsperre Agger, sits immediately upstream and "
        "functions as a settling and quality buffer before water enters the "
        "main reservoir. Water temperature and quality data are published by "
        "the Wupperverband's online portal, which shows the Agger system "
        "consistently meeting EU drinking water source quality guidelines. "
        "During the dry summers of 2018–2022 the reservoir experienced marked "
        "drawdown, exposing the concrete wave-protection apron along the "
        "upstream face of the dam and reducing the bathing beach access area."
    ),
    "Oker": (
        "The Okertalsperre in the western Harz mountains of Lower Saxony holds "
        "46.6 million cubic metres and forms the centrepiece of the Harzwasserwerke "
        "reservoir system. Completed in 1956, the 63-metre concrete double-arch "
        "gravity dam impounds the Oker river — the main drainage artery of the "
        "western Harz — just above the town of Schulenberg im Oberharz. The "
        "Okertalsperre is the primary drinking water source for the Braunschweig, "
        "Wolfenbüttel, and Salzgitter regions, supplying treated water to roughly "
        "700,000 people in the Lower Saxony industrial heartland. The reservoir "
        "works in an interconnected system with the Innerste, Grane, Söse, and "
        "Oder reservoirs across the Harz, enabling water transfers between "
        "catchments during drought or maintenance periods. The steep Okertal "
        "gorge below the dam is a designated nature reserve, and the stretch of "
        "the Oker river immediately downstream of the dam supports important "
        "populations of brown trout and rare aquatic invertebrates dependent on "
        "cold, well-oxygenated release flows. The Harzwasserwerke manages the "
        "ecological minimum flow regime to protect downstream habitat. The "
        "reservoir valley is surrounded by the western Harz national park boundary "
        "and the forested hillsides above the waterline support Germany's largest "
        "breeding population of black stork."
    ),
}


def get_de_dam_description(name_en: str) -> str:
    """Return the prose description for a German reservoir by its ASCII name_en key.

    Falls back to a generic placeholder if the key is not found — this avoids
    KeyErrors from data inconsistencies between the DB and description dict.
    """
    return DE_DAM_DESCRIPTIONS.get(
        name_en,
        f"{name_en} is a reservoir in Germany. Detailed information about this "
        "reservoir will be added in a future update.",
    )
