"""
Unique prose descriptions for Spain's 20 largest reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.
"""
from __future__ import annotations

ES_DAM_DESCRIPTIONS: dict[str, str] = {
    "La Serena": (
        "La Serena is the largest reservoir in Spain and one of the largest in "
        "Western Europe, located in the province of Badajoz in Extremadura on the "
        "Zújar river, a major tributary of the Guadiana. Completed in 1990, the "
        "gravity dam stands 60 metres tall and holds a total capacity of 3,219 "
        "million cubic metres, making it a critical piece of water infrastructure "
        "for the arid interior of the Iberian Peninsula. The reservoir serves "
        "multiple purposes: irrigation for the extensive agricultural lands of "
        "the Guadiana basin, hydroelectric power generation, water supply for "
        "surrounding communities, and flood control during the intense autumn and "
        "winter rainfall events that periodically affect Extremadura. La Serena's "
        "vast surface area — nearly 14,000 hectares when full — creates one of "
        "the largest artificial lakes in Europe, supporting a rich ecosystem of "
        "waterbirds and fish. The surrounding landscape of dehesa (Mediterranean "
        "oak woodland) and dry grassland gives the reservoir a distinctive "
        "character. The dam's construction was part of the Guadiana Hydrological "
        "Plan, which aimed to regulate the highly variable flow regime of the "
        "river system and support agricultural development in one of Spain's "
        "least economically developed regions."
    ),
    "Alcantara": (
        "Alcántara dam sits on the Tajo (Tagus) river in the province of Cáceres, "
        "Extremadura, just upstream of the historic Roman bridge of Alcántara — "
        "one of the finest surviving examples of Roman engineering. Completed in "
        "1969, the gravity dam is 130 metres tall and impounds 3,160 million cubic "
        "metres, making it the second-largest reservoir in Spain. Alcántara is "
        "primarily a hydroelectric facility, housing one of Spain's largest "
        "hydropower plants. The reservoir occupies a deep, narrow gorge carved "
        "by the Tagus through the granite bedrock of western Extremadura, creating "
        "a long, sinuous lake that extends upstream for over 90 kilometres. The "
        "Tagus is the longest river in the Iberian Peninsula, and Alcántara's "
        "position near the Portuguese border makes it a key element in the "
        "international management of the river's flow. Water released from "
        "Alcántara flows downstream into Portugal, where it feeds additional "
        "reservoirs before reaching the Atlantic at Lisbon. The dam's operation "
        "is therefore coordinated under the Albufeira Convention, the bilateral "
        "water-sharing agreement between Spain and Portugal."
    ),
    "Almendra": (
        "Almendra is a remarkable arch dam on the Tormes river in the province "
        "of Salamanca, Castilla y León. At 202 metres, it is one of the tallest "
        "dams in Europe and the tallest in Spain. Completed in 1970, the double-"
        "curvature arch dam holds 2,649 million cubic metres — the third-largest "
        "reservoir in Spain. Almendra was built primarily for hydroelectric power "
        "generation and forms part of the Duero river system's cascade of dams "
        "that produce a significant share of Spain's renewable energy. The "
        "reservoir sits in a remote, sparsely populated area of western "
        "Salamanca, where the Tormes river has carved a deep canyon through "
        "ancient granitic rock. The dam's extraordinary height and elegant arch "
        "form make it an engineering landmark. Downstream, the water flows "
        "through the Aldeadávila dam — another major hydroelectric facility — "
        "before entering Portugal. The Tormes river itself is famous in Spanish "
        "literature, flowing through the university city of Salamanca and "
        "referenced in the picaresque novel 'Lazarillo de Tormes'."
    ),
    "Buendia": (
        "Buendía reservoir is located in the province of Cuenca, Castilla-La "
        "Mancha, on the Guadiela river, a tributary of the upper Tagus. "
        "Completed in 1958, the gravity dam holds 1,705 million cubic metres "
        "and, together with the neighbouring Entrepeñas reservoir, forms the "
        "system known as the 'Mar de Castilla' (Sea of Castile) — a vast "
        "expanse of water in the otherwise dry Castilian plateau. Buendía is "
        "famous in Spanish water politics as one of the two headwater reservoirs "
        "of the Tajo-Segura water transfer (Trasvase Tajo-Segura), a massive "
        "infrastructure project completed in 1979 that diverts water from the "
        "relatively water-rich upper Tagus to the arid southeast of Spain "
        "(Murcia, Alicante, Almería). The transfer is one of the most "
        "contentious water policy issues in Spain, with Castilla-La Mancha "
        "arguing that it depletes their water resources while the southeast "
        "depends on it for agriculture and drinking water. Buendía's water "
        "levels are therefore scrutinised not just for local water management "
        "but as a barometer of the ongoing political debate over inter-basin "
        "water transfers in Spain."
    ),
    "Cijara": (
        "Cíjara is a large gravity dam on the Guadiana river in the province "
        "of Badajoz, Extremadura, near the border with Ciudad Real. Completed "
        "in 1956, it holds 1,505 million cubic metres and is the first major "
        "reservoir in the Guadiana basin's chain of dams, followed downstream "
        "by García de Sola, Orellana, and eventually La Serena on the Zújar "
        "tributary. Cíjara serves irrigation, hydroelectric, and flood control "
        "purposes. The reservoir is surrounded by the Cíjara National Hunting "
        "Reserve, one of the largest protected hunting estates in Spain, "
        "covering over 25,000 hectares of Mediterranean forest. The area "
        "supports populations of red deer, wild boar, and Iberian lynx."
    ),
    "Valdecanas": (
        "Valdecañas dam is an arch-gravity structure on the Tagus river in "
        "the province of Cáceres, Extremadura. Completed in 1964, it holds "
        "1,446 million cubic metres and is a key component of the Tagus "
        "river's hydroelectric cascade. The reservoir is perhaps best known "
        "in recent years for the controversial Marina Isla de Valdecañas "
        "luxury resort development, which was built on a small island in the "
        "reservoir in a protected natural area. The Spanish courts ordered "
        "its partial demolition in a landmark environmental ruling. Beyond "
        "the controversy, Valdecañas is an important water regulation "
        "structure for the middle Tagus, managing the variable flows from "
        "the Castilian headwaters and coordinating releases with downstream "
        "reservoirs including Alcántara and, ultimately, Portugal."
    ),
    "Mequinenza": (
        "Mequinenza dam sits at the confluence of the Ebro and Segre rivers "
        "in the province of Zaragoza, Aragón. Completed in 1966, the gravity "
        "dam holds 1,373 million cubic metres — the largest reservoir in the "
        "Ebro basin. The reservoir, known locally as the 'Mar de Aragón' "
        "(Sea of Aragon), stretches over 110 kilometres upstream and is "
        "renowned internationally as one of Europe's premier sport fishing "
        "destinations, particularly for catfish (siluro) and carp. The dam "
        "is a major hydroelectric facility, and its position near the "
        "junction of the Ebro's two largest tributaries gives it a strategic "
        "role in managing the basin's water resources. The town of Mequinenza "
        "was partially submerged by the reservoir's creation, and the "
        "community was relocated — an experience chronicled in the novels "
        "of local author Jesús Moncada."
    ),
    "Ricobayo": (
        "Ricobayo is an arch dam on the Esla river in the province of Zamora, "
        "Castilla y León. Originally completed in 1934, it was one of the "
        "first large hydroelectric dams built in Spain and holds 1,145 million "
        "cubic metres. The dam was heightened in the 1990s to increase its "
        "capacity. Ricobayo is a purely hydroelectric facility and forms part "
        "of the Duero basin's extensive hydropower system. The Esla is one of "
        "the most powerful rivers in the Duero catchment, and Ricobayo's "
        "substantial storage capacity makes it valuable for managing seasonal "
        "flow variations. The reservoir lies in the sparsely populated "
        "Zamoran countryside, an area of gentle hills, cereal agriculture, "
        "and traditional pastoral farming."
    ),
    "Iznajar": (
        "Iznájar is an arch dam on the Genil river in southern Spain, straddling "
        "the provinces of Córdoba and Granada in Andalusia. Completed in 1969, "
        "it holds 920 million cubic metres — the largest reservoir in Andalusia "
        "and the largest in the Guadalquivir basin. The reservoir is nicknamed "
        "the 'Lago de Andalucía' (Lake of Andalusia) and is one of the most "
        "important water resources in southern Spain, providing irrigation water "
        "for the olive groves and agricultural lands of the Guadalquivir valley "
        "as well as drinking water for Córdoba and surrounding communities. The "
        "picturesque town of Iznájar overlooks the reservoir from a dramatic "
        "hilltop position, and the area has become a popular destination for "
        "water sports and tourism. The Genil, which rises in the Sierra Nevada "
        "near Granada, is the Guadalquivir's largest tributary."
    ),
    "Gabriel y Galan": (
        "Gabriel y Galán reservoir is located on the Alagón river in the province "
        "of Cáceres, Extremadura. Completed in 1961, the gravity dam holds 911 "
        "million cubic metres and is named after the poet José María Gabriel y "
        "Galán, who lived in the region. The reservoir is a major irrigation "
        "source for the fertile agricultural lands of the Alagón valley, "
        "supporting intensive cultivation of tobacco, peppers, and other crops. "
        "The dam also provides flood protection for the downstream towns along "
        "the Alagón before it joins the Tagus. The reservoir's shores are "
        "popular for recreational activities, particularly during the hot "
        "Extremaduran summers."
    ),
    "Alange": (
        "Alange reservoir is located on the Matachel river near the Roman city "
        "of Mérida in the province of Badajoz, Extremadura. Completed in 1992, "
        "the gravity dam holds 852 million cubic metres. The town of Alange, "
        "which gives the reservoir its name, is famous for its Roman thermal "
        "baths — among the best preserved in Spain — reflecting thousands of "
        "years of human settlement attracted by the area's water resources. "
        "The reservoir primarily serves irrigation, feeding the extensive "
        "agricultural systems of the Vegas Bajas del Guadiana, one of "
        "Extremadura's most productive farming areas."
    ),
    "La Brena II": (
        "La Breña II is a gravity dam on the Guadiato river in the province "
        "of Córdoba, Andalusia. Completed in 2009, it is one of Spain's newest "
        "major dams, replacing and greatly expanding the original La Breña dam "
        "(1932). With a capacity of 823 million cubic metres, it serves water "
        "supply for Córdoba city and surrounding municipalities, irrigation "
        "for the Guadalquivir valley, and flood control on the Guadiato. The "
        "modern design incorporates environmental flow requirements and fish "
        "passage facilities reflecting contemporary dam engineering standards."
    ),
    "Entrepenas": (
        "Entrepeñas is an arch dam on the upper Tagus river in the province "
        "of Guadalajara, Castilla-La Mancha. Completed in 1956, it holds 813 "
        "million cubic metres and, together with the adjacent Buendía reservoir, "
        "forms the headwater storage system of the Tajo-Segura water transfer. "
        "The combined Entrepeñas-Buendía system is a focal point of Spanish "
        "water politics, as its levels determine whether inter-basin transfers "
        "to southeastern Spain can proceed. The reservoir sits in a dramatic "
        "landscape of limestone gorges and plateaux, and the area has become a "
        "popular inland tourism destination."
    ),
    "Orellana": (
        "Orellana is a gravity dam on the Guadiana river in the province of "
        "Badajoz, Extremadura. Completed in 1963, it holds 808 million cubic "
        "metres and sits downstream of Cíjara and García de Sola in the "
        "Guadiana's chain of major reservoirs. Orellana serves irrigation and "
        "hydroelectric purposes. The reservoir's relatively shallow, wide "
        "profile creates extensive shoreline habitats and the area is designated "
        "as a Special Protection Area for birds under EU environmental law, "
        "supporting important breeding populations of herons, storks, and "
        "other waterbirds."
    ),
    "Canelles": (
        "Canelles is an arch dam on the Noguera Ribagorzana river on the border "
        "between the provinces of Huesca (Aragón) and Lleida (Catalonia). "
        "Completed in 1960, it holds 679 million cubic metres and stands 150 "
        "metres tall in a spectacular limestone gorge. The dam is a major "
        "hydroelectric facility and part of the Noguera Ribagorzana's cascade "
        "of dams that exploit the steep gradient from the Pyrenees to the Ebro "
        "valley. The reservoir sits in remote, rugged terrain near the Pyrenean "
        "foothills, and the dramatic gorge setting makes it one of the most "
        "visually striking dam sites in Spain."
    ),
    "Riano": (
        "Riaño is an arch dam on the Esla river in the province of León, "
        "Castilla y León. Completed in 1987 after decades of controversy, it "
        "holds 641 million cubic metres. The construction of Riaño required "
        "the flooding of seven villages in the Esla valley, an event that "
        "generated intense local opposition and remains a painful memory in "
        "the region. Despite the social cost, Riaño provides vital irrigation "
        "water for the agricultural lands of the Duero basin, drinking water "
        "for León, and hydroelectric power. The reservoir is set against the "
        "backdrop of the Cantabrian Mountains, near the Picos de Europa "
        "National Park, in some of the most dramatic mountain scenery in Spain."
    ),
    "Andevalo": (
        "Andévalo is a rockfill dam on the Chanza river in the province of "
        "Huelva, Andalusia, near the Portuguese border. Completed in 2004, "
        "it holds 634 million cubic metres and is one of Spain's most recent "
        "major reservoir constructions. The dam serves primarily for water "
        "supply to the mining and industrial areas of the Andévalo comarca "
        "and for environmental flow maintenance in the cross-border Guadiana "
        "basin. The reservoir's location near the Portuguese frontier means "
        "its operation is coordinated under the Albufeira Convention."
    ),
    "Negratin": (
        "Negratín is an arch dam on the Guadiana Menor river in the province "
        "of Granada, Andalusia. Completed in 1984, it holds 571 million cubic "
        "metres and is the largest reservoir in the eastern Guadalquivir basin. "
        "The dam serves irrigation, water supply, and flood control purposes. "
        "The reservoir sits in an arid, striking landscape of badlands and "
        "eroded terrain, and has become known for water sports and tourism. "
        "The Guadiana Menor drains the semi-arid highlands of eastern Andalusia "
        "before joining the Guadalquivir."
    ),
    "Garcia de Sola": (
        "García de Sola (also known as Puerto Peña) is a gravity dam on the "
        "Guadiana river in the province of Badajoz, Extremadura. Completed in "
        "1963, it holds 554 million cubic metres and sits between Cíjara "
        "upstream and Orellana downstream in the Guadiana's chain of major "
        "reservoirs. The dam serves hydroelectric and irrigation purposes. The "
        "reservoir lies in a relatively narrow valley, and the surrounding "
        "landscape of Mediterranean scrubland supports diverse wildlife "
        "including populations of Iberian imperial eagle and black vulture."
    ),
    "Embalse del Ebro": (
        "The Ebro reservoir is located near the headwaters of the Ebro river "
        "in the province of Cantabria, close to the border with Burgos. "
        "Completed in 1952, the gravity dam holds 541 million cubic metres "
        "and is the most upstream major reservoir on Spain's most voluminous "
        "river. Despite its relatively modest capacity by national standards, "
        "the Ebro reservoir occupies a strategic position at the head of the "
        "river system, regulating flows that supply the extensive irrigation "
        "networks of the middle and lower Ebro valley in Aragón and Catalonia. "
        "The reservoir sits at relatively high altitude in the Cantabrian "
        "Mountains, receiving abundant rainfall from Atlantic weather systems."
    ),
}


def get_es_dam_description(name_en: str) -> str:
    """Return the prose description for a Spanish dam, or empty string if not found."""
    return ES_DAM_DESCRIPTIONS.get(name_en, "")
