"""
Unique prose descriptions for Finland's 15 largest regulated lakes.
Used on dam detail pages to provide SEO-friendly, human-readable context.

Finnish "dams" are mostly regulated natural lakes — vast water bodies shaped
by glaciation and managed for hydroelectric power, flood control, and water supply.
"""
from __future__ import annotations

FI_DAM_DESCRIPTIONS: dict[str, str] = {
    "Inarijarvi": (
        "Inarijärvi is Finland's third-largest lake and the country's most significant "
        "regulated natural water body, lying deep within the Arctic wilderness of Lapland "
        "close to the Norwegian and Russian borders. Covering approximately 1,040 square "
        "kilometres, this vast subarctic lake was first regulated in 1942 to support "
        "hydroelectric power generation on the Paatsjoki river system. With a total water "
        "volume of around 15,000 million cubic metres, Inarijärvi ranks among the largest "
        "freshwater reservoirs in the whole of Scandinavia. The lake lies at an elevation "
        "of roughly 119 metres above sea level and is frozen for up to six months of the "
        "year. Its shores are home to the indigenous Sámi people, who have fished and "
        "herded reindeer here for thousands of years. The lake's exceptional clarity, "
        "remote wilderness character, and abundant Arctic char and brown trout populations "
        "make it a prized destination for anglers from across Europe. Regulation of the "
        "water level is carefully balanced against the ecological needs of the lake, "
        "fish spawning habitats, and the cultural rights of the Sámi. Inarijärvi also "
        "serves as a critical freshwater reserve for the surrounding region."
    ),
    "Saimaa": (
        "Saimaa is the largest lake in Finland and the fourth-largest natural freshwater "
        "lake in Europe, forming the heart of the Finnish Lakeland in the South Savo and "
        "Karelia regions. Stretching across more than 4,400 square kilometres with a "
        "labyrinthine coastline of some 14,000 kilometres, Saimaa is not a single lake "
        "but an interconnected system of water bodies drained by the Vuoksi river into "
        "Lake Ladoga in Russia. Regulation began in 1896 with the construction of the "
        "Tainionkoski sluice and was significantly modernised in subsequent decades to "
        "manage seasonal flooding in Savonlinna and other lakeside cities. With a water "
        "volume of approximately 9,000 million cubic metres, Saimaa is a critical "
        "freshwater resource for eastern Finland. It is also the only habitat of the "
        "critically endangered Saimaa ringed seal, a relic species from the Ice Age that "
        "became isolated when the lake was cut off from the Baltic sea. Conservation "
        "efforts for the seal directly influence water regulation schedules, making "
        "Saimaa one of the few lakes in the world where hydropower management is "
        "explicitly co-governed with wildlife protection. The lake district surrounding "
        "Saimaa draws millions of visitors annually."
    ),
    "Paijanne": (
        "Päijänne is Finland's second-largest lake and one of the deepest, reaching "
        "down to 95 metres in places within the Central Finland and Päijät-Häme regions. "
        "The lake stretches nearly 120 kilometres from north to south and drains via the "
        "Kymijoki river into the Gulf of Finland. Regulation for hydroelectric power "
        "production began in earnest after 1964 and is managed through a series of dams "
        "and weirs on the Kymijoki. With an estimated water volume of 4,000 million cubic "
        "metres, Päijänne is the primary drinking water source for the Helsinki metropolitan "
        "area, supplied through the Päijänne Water Tunnel — at 120 kilometres the longest "
        "rock tunnel in the world. The tunnel was constructed in the 1970s and 1980s and "
        "delivers up to 18 million litres of water daily to over one million people. The "
        "lake's regulated water levels are carefully managed to ensure adequate tunnel "
        "inflow while protecting shoreline ecosystems and the livelihoods of fishing "
        "communities. Päijänne is also a popular summer destination for sailing, "
        "kayaking, and cottage tourism."
    ),
    "Oulujarvi": (
        "Oulujärvi is the fifth-largest lake in Finland and the largest in Ostrobothnia, "
        "sitting at the heart of the Oulujoki river system in North Ostrobothnia. "
        "Covering around 900 square kilometres, the lake was brought under regulation in "
        "1951 as part of Finland's post-war industrialisation drive, which harnessed the "
        "Oulujoki's significant hydropower potential. Today the river is one of Finland's "
        "most intensively regulated waterways, with a series of seven power stations "
        "between Oulujärvi and the Gulf of Bothnia. The reservoir holds approximately "
        "2,500 million cubic metres of water and plays a dual role in flood control and "
        "energy production. Regulation has dramatically altered the natural flow regime "
        "of the Oulujoki, and the original migratory Atlantic salmon population was lost. "
        "Ongoing restoration and stocking programmes aim to re-establish fish populations "
        "in some tributaries. The lake's shores support several towns, and Kajaani, the "
        "regional centre of Kainuu, sits at the eastern tip of the lake system."
    ),
    "Lokka": (
        "Lokka is one of the largest artificial reservoirs in Finland and the whole of "
        "the Nordic countries, created between 1965 and 1967 by flooding a vast area of "
        "Lapland wilderness for hydroelectric power on the Luiro river. The reservoir "
        "covers approximately 417 square kilometres when at full supply level and holds "
        "around 1,400 million cubic metres of water. The dam stands 11 metres in height "
        "and was built at a cost that included the forced relocation of Sámi reindeer "
        "herding communities who had lived in the flooded valleys for generations. The "
        "submerged landscape included rich wetlands, traditional grazing areas, and the "
        "village of Lokka itself. Lokka Reservoir is operated in concert with the "
        "neighbouring Porttipahta reservoir, with both feeding into the Kemijoki river "
        "system and ultimately the Kemijoki power stations. The reservoir's remote Lapland "
        "location makes it an important wilderness destination; it hosts nationally "
        "significant populations of whooper swans, osprey, and other wetland birds that "
        "have colonised the shallower margins of the flooded area over the decades."
    ),
    "Porttipahta": (
        "Porttipahta is the second-largest artificial reservoir in Finland, built between "
        "1967 and 1970 on a tributary of the Kemijoki in Finnish Lapland. The 35-metre-high "
        "earth-fill dam impounds approximately 1,350 million cubic metres of water across "
        "an area of around 214 square kilometres. Like its sister reservoir Lokka, "
        "Porttipahta was created by flooding a large area of Sámi traditional territory, "
        "displacing families and submerging reindeer pastures. Together, Lokka and "
        "Porttipahta form the core of the Kemijoki hydropower system, the most powerful "
        "river system in Finland, providing a significant share of Finnish domestic "
        "electricity generation. The reservoir sits at an elevation of around 244 metres "
        "above sea level and is seasonally ice-covered for much of the year. Porttipahta "
        "is valued for fishing, particularly brown trout and grayling that thrive in the "
        "cold, nutrient-poor Arctic waters. The surrounding landscape of fell birch "
        "forests and open fells is characteristic of the northern boreal and sub-Arctic "
        "zones."
    ),
    "Pielinen": (
        "Pielinen is the fourth-largest lake in Finland, lying in the North Karelia region "
        "and forming part of the Vuoksi river system that ultimately drains into Lake "
        "Ladoga. The lake stretches 90 kilometres from north to south and covers over "
        "900 square kilometres. Regulation of Pielinen began in 1970 with the construction "
        "of the Kaltimo power station at the outlet at Pielisjoki, bringing the natural "
        "water level fluctuations under controlled management for the first time. The "
        "reservoir holds approximately 1,100 million cubic metres. Pielinen is surrounded "
        "by some of the most scenically dramatic lake-and-fell countryside in Finland, "
        "including the famous Koli National Park on its western shore, whose ancient spruce "
        "and pine forests inspired the Finnish national romantic movement of the 19th "
        "century. The composer Jean Sibelius and painter Eero Järnefelt both visited Koli "
        "and drew inspiration from the sweeping views over Pielinen. The lake remains "
        "lightly regulated compared to many Finnish reservoirs and supports a healthy "
        "ecology of pike, perch, and pikeperch."
    ),
    "Kemijarvi": (
        "Kemijärvi is the most northerly regulated lake in Finland that is also a "
        "significant settlement centre, with the town of Kemijärvi sitting directly on "
        "its shores in northern Lapland. The lake covers around 240 square kilometres "
        "and was brought under regulation in 1965 as part of the Kemijoki hydropower "
        "development programme, raising the natural water level by several metres to "
        "increase the storage capacity of the river system. The reservoir holds "
        "approximately 850 million cubic metres. Kemijärvi lies at around 148 metres "
        "above sea level and is the headwater reservoir of the entire Kemijoki power "
        "cascade, which generates roughly a fifth of Finland's hydroelectric output. "
        "The town of Kemijärvi was once an important sawmill and timber-floating centre; "
        "today it serves as a gateway to skiing at Suomutunturi and wilderness tourism "
        "in the surrounding Lapland forests. The lake is a popular ice-fishing destination "
        "in winter, with vendace and brown trout among the most sought-after species."
    ),
    "Nasijarvi": (
        "Näsijärvi is a large lake in the Pirkanmaa region of southern Finland, directly "
        "adjacent to the city of Tampere. Covering approximately 257 square kilometres, "
        "the lake is one of the oldest regulated water bodies in Finland, with water "
        "level control dating back to 1872 when the Tammerkoski rapids were harnessed "
        "for industrial milling. The reservoir holds an estimated 320 million cubic metres. "
        "Näsijärvi forms part of the Kokemäenjoki river system, flowing southward via "
        "the Nokianvirta channel. Tampere, Finland's second city, developed at the "
        "narrow isthmus between Näsijärvi and the lower lake Pyhäjärvi, taking advantage "
        "of the natural head difference for early industrial water power. Today the "
        "Näsijärvi shoreline within Tampere is characterised by parks, cultural venues, "
        "and the distinctive Näsinneula observation tower. The lake supports commercial "
        "and recreational fishing, with a passenger boat service operating to lakeside "
        "villages throughout the summer season."
    ),
    "Pyhajarvi": (
        "Pyhäjärvi near Säkylä is one of the most important lakes in southwestern "
        "Finland, lying in the Satakunta region and draining via the Eurajoki river into "
        "the Gulf of Bothnia. Covering approximately 154 square kilometres, the lake was "
        "regulated from 1958 onwards to support water supply, flood control, and modest "
        "hydropower generation. The reservoir holds an estimated 250 million cubic metres. "
        "Pyhäjärvi is the primary raw water source for a significant part of southwestern "
        "Finland's municipal water supply network, including the cities of Turku, Pori, "
        "and Rauma collectively through the Lounais-Suomen Vesi water utility. The lake's "
        "relatively shallow depth and fertile catchment have historically made it "
        "vulnerable to eutrophication; intensive water quality monitoring and catchment "
        "management programmes have been in place since the 1980s. Pyhäjärvi is also "
        "celebrated for its vendace fishery, supporting a significant commercial harvest "
        "of Finland's beloved smoked vendace (muikku)."
    ),
    "Ontojarvi": (
        "Ontojärvi is a regulated lake in the Kainuu region of eastern Finland, forming "
        "part of the Oulujoki river system. Covering around 90 square kilometres, the lake "
        "was brought under regulation in 1951 as part of the same post-war hydropower "
        "programme that transformed the entire Oulujoki basin. The reservoir holds "
        "approximately 250 million cubic metres. Ontojärvi is connected to the broader "
        "Oulujoki system through the Ontojoki river and feeds into a series of downstream "
        "power stations. The surrounding Kainuu region is characterised by vast boreal "
        "forests, and the Ontojärvi basin forms part of the larger wilderness landscape "
        "that makes Kainuu one of Finland's least densely populated and most pristine "
        "regions. The lake supports fishing for pike, perch, and brown trout, and the "
        "shoreline forests are valued for elk and bear hunting. Water level fluctuations "
        "from hydropower regulation have shaped the character of the shoreline over "
        "decades, creating characteristic drawdown zones."
    ),
    "Nuasjarvi": (
        "Nuasjärvi is part of the Oulujoki hydropower chain in the Kainuu region, "
        "connected to the wider lake system that includes Ontojärvi and Kiantajärvi. "
        "The lake covers approximately 70 square kilometres and was regulated in 1951 "
        "along with the other Oulujoki basin lakes. The reservoir holds around 200 million "
        "cubic metres. Nuasjärvi feeds into the downstream Oulujoki power stations and "
        "plays an important role in smoothing seasonal water flow variations across the "
        "system. The town of Sotkamo lies on the shores of Nuasjärvi and is a major "
        "tourism and winter sports centre, hosting the Vuokatti sports resort and "
        "international biathlon and cross-country skiing events. Kajaani, the regional "
        "capital of Kainuu, is accessible via the Kajaaninjoki river that links Nuasjärvi "
        "westward. The lake is known for good ice-fishing conditions in winter and "
        "recreational boating in summer."
    ),
    "Kiantajarvi": (
        "Kiantajärvi is a regulated lake in the Suomussalmi municipality of Kainuu, "
        "in the eastern borderlands of Finland close to Russia. Covering around 220 "
        "square kilometres, the lake was regulated in 1964 as part of the Emäjoki and "
        "Oulujoki system development. The reservoir holds approximately 430 million cubic "
        "metres and discharges via the Emäjoki into the larger Oulujoki basin. "
        "Suomussalmi is historically significant as the site of a major battle during the "
        "1939–1940 Winter War, where Finnish forces halted a Soviet invasion — an event "
        "commemorated at the nearby Raate Road open-air museum. The Kiantajärvi area is "
        "remote and heavily forested, characteristic of the vast Kainuu wilderness. Brown "
        "bear, wolf, wolverine, and lynx all inhabit the surrounding forests. The lake is "
        "popular for wilderness fishing, canoeing, and hunting, and the composer Jean "
        "Sibelius reportedly drew inspiration from the Kainuu landscape during his visits "
        "to the region."
    ),
    "Vuokkijarvi": (
        "Vuokkijärvi is a regulated lake in the Kuhmo municipality of Kainuu, in the "
        "eastern lake district near the Russian border. Covering around 60 square "
        "kilometres, the lake was regulated in 1964 as part of the broader Oulujoki "
        "hydropower programme. The reservoir holds approximately 170 million cubic metres. "
        "Vuokkijärvi feeds into the Vuokkijoki, which connects it to the larger Oulujoki "
        "basin. The surrounding Kuhmo region is renowned as one of the best areas in "
        "Finland for wildlife watching, particularly brown bear and wolverine, which can "
        "be observed from purpose-built hides in the forests east of the lake. Kuhmo is "
        "also famous as the home of the annual Kuhmo Chamber Music Festival, one of "
        "Finland's most celebrated classical music events held each July. The lake's "
        "remote location and minimal development make it a pristine wilderness water body, "
        "with excellent fishing for pike and perch."
    ),
    "Koitere": (
        "Koitere is a regulated lake in the North Karelia region of eastern Finland, "
        "draining via the Koitajoki river into Pielinen and ultimately into the Vuoksi "
        "system. Covering approximately 164 square kilometres, the lake was regulated in "
        "1955 when the Pamilonkoski power station was constructed on the Koitajoki outlet. "
        "The reservoir holds around 170 million cubic metres. Koitere lies within one of "
        "the most ecologically valuable boreal forest landscapes in Finland; the adjacent "
        "Petkeljärvi–Putkelanharju National Park protects an ancient esker ridge system "
        "with exceptional biodiversity. The lake's waters drain through old-growth spruce "
        "and pine forests that shelter significant populations of white-tailed eagle, "
        "black stork, and lesser spotted woodpecker. The regulation regime on Koitere "
        "is considered relatively gentle compared to more intensively managed Finnish "
        "reservoirs, and the lake retains a largely natural ecological character. "
        "The Koitajoki valley is also significant for Karelian cultural heritage."
    ),
}


def get_fi_dam_description(name_en: str) -> str:
    """Return the prose description for a Finnish reservoir, or a generic fallback."""
    return FI_DAM_DESCRIPTIONS.get(
        name_en,
        f"{name_en} is a regulated water body in Finland monitored by the "
        f"Finnish Environment Institute (SYKE). Water level data is collected "
        f"daily from hydrological monitoring stations.",
    )
