"""
Unique prose descriptions for each of the 4 major Greek reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.
"""
from __future__ import annotations

GR_DAM_DESCRIPTIONS: dict[str, str] = {
    "Mornos": (
        "Mornos is the largest water supply reservoir in Greece, located in Phocis in central "
        "Greece on the Mornos River. Built in 1979, the earth-fill dam stands 126 metres tall "
        "and holds a capacity of 780 million cubic metres — a strategic cornerstone of water "
        "infrastructure for the greater Athens metropolitan region. Water from Mornos reaches "
        "Athens through the Mornos-Athens Aqueduct, a remarkable engineering feat consisting of "
        "105 kilometres of underground tunnel that carries approximately 40% of Attica's total "
        "water supply to the 3.7 million residents of the Athens metropolitan area. The Mornos "
        "River catchment drains the Phocis mountains and the eastern slopes of the Pindus range, "
        "a zone that receives moderate to heavy winter rainfall, particularly when Atlantic "
        "frontal systems track across the eastern Mediterranean. For decades, Mornos functioned "
        "as a resilient buffer against drought, routinely reaching full capacity in wet years. "
        "However, the intensifying regional water scarcity of recent years has put exceptional "
        "pressure on the reservoir. In October 2025, Mornos hit its lowest level in 15 years, "
        "dropping to approximately 45% below the previous year's level — a sharp decline that "
        "prompted emergency measures across the Attica water system and raised public concern "
        "about long-term water security for the capital. In response, the Greek government "
        "announced a comprehensive €2.5 billion water investment plan in October 2025 that "
        "includes infrastructure improvements, enhanced monitoring systems, and investment in "
        "alternative water sources such as desalination. Mornos remains the vital heart of "
        "Athens's water supply, and its reservoir levels are scrutinised constantly by water "
        "managers, civil engineers, and the broader public — when Mornos is healthy, Attica's "
        "water future seems secure; when it runs low, the urgency of regional water planning "
        "becomes painfully apparent."
    ),
    "Yliki": (
        "Yliki is a naturally occurring lake that was enlarged to serve as a major water storage "
        "reservoir, situated in Boeotia in central Greece between the Helicon and Cithaeron mountain "
        "ranges. With a capacity of 600 million cubic metres, Yliki is the second-largest water "
        "source in the greater Athens region after Mornos. Like Mornos, water from Yliki reaches "
        "Athens through the same Mornos-Athens Aqueduct, feeding into the same integrated water "
        "transfer network that supplies Attica. The transformation of the natural Yliki lake into "
        "a managed reservoir reflects the broader Greek water engineering efforts of the late "
        "twentieth century — enhancing natural features to serve modern metropolitan demand. "
        "The water body has historical significance stretching back to antiquity: the ancient "
        "Greeks knew the lake as one of the major water sources of Boeotia, and it features in "
        "classical texts alongside references to the neighbouring Lake Copais. The Yliki catchment "
        "drains portions of the Helicon and Cithaeron massifs, receiving winter rainfall from the "
        "same synoptic weather patterns that feed Mornos. During wet years, Yliki contributes "
        "substantially to Athens's total supply, allowing water managers to reduce the drawdown "
        "pressure on Mornos. Conversely, during extended drought periods, Yliki's level can fall "
        "sharply, and the two reservoirs function as interdependent elements of a single supply "
        "system. The lake's surroundings — the Boeotian plateau with its ancient cities, vineyards, "
        "and agricultural land — reflect thousands of years of human settlement. Yliki's ecological "
        "role includes supporting fish populations and waterfowl, and the lake has attracted modest "
        "tourism interest. As drought pressures intensify across Greece, Yliki's supplementary role "
        "in the Athens water system becomes increasingly valued by water resource planners."
    ),
    "Evinos": (
        "Evinos is the newest of the four major reservoirs supplying the Athens water system, "
        "located in Aetolia-Acarnania in western Greece along the Evinos River. Completed in 2001, "
        "the reservoir was built explicitly as a response to the prolonged water crises that gripped "
        "Athens during the 1990s, when an extended drought sequence exhausted conventional storage "
        "and forced emergency rationing. The arch dam is 125 metres tall and impounds 130 million "
        "cubic metres of water — a capacity more modest than Mornos or Yliki, but strategically "
        "important. Water from Evinos flows into the existing Mornos Reservoir via a 30-kilometre "
        "tunnel connection, functioning as a supplementary feed into the integrated Athens water "
        "network. The Evinos River catchment drains the western Aetolia mountains, a zone that "
        "receives significant winter precipitation and benefits from orographic lifting as "
        "Atlantic-origin storm systems encounter the rising terrain. The newer construction date "
        "of Evinos meant it benefited from modern dam engineering practices, sophisticated "
        "instrumentation systems, and automated monitoring capabilities that older Greek dams "
        "predate. Compared to the lengthy history of Mornos and the ancient roots of Yliki, Evinos "
        "is a contemporary addition to Greece's water infrastructure, yet it has proven its value "
        "during recent drought periods. The dam itself is a modern arch structure, a different "
        "design class from the earth-fill dams that dominate the system. The reservoir's "
        "mountainous setting and remote location mean it receives fewer visitors than Mornos or "
        "Yliki, but it remains a crucial element in the diversified strategy for meeting Athens's "
        "water demand. As climate projections point toward increasingly variable rainfall patterns "
        "across the eastern Mediterranean, the role of Evinos as a secondary source feeding the "
        "primary Mornos-Yliki system has become more strategically important."
    ),
    "Marathon": (
        "Marathon dam is one of the oldest modern dams in Greece, built in 1929 to provide water "
        "for Athens at a time when the city was beginning to expand beyond the capacity of local "
        "groundwater and small-scale sources. Located approximately 40 kilometres northeast of "
        "Athens on the Marathon River, the reservoir holds only 41 million cubic metres — by far "
        "the smallest of the four major Athens water sources. Yet Marathon holds a historical and "
        "cultural significance entirely disproportionate to its storage volume. The concrete gravity "
        "dam is distinctively faced with Pentelic marble, quarried from the same Hymettus slopes "
        "that yielded the white marble used to construct the Parthenon in ancient Athens. This "
        "choice of material transformed a utilitarian piece of infrastructure into an architectural "
        "landmark of aesthetic merit. The dam sits near the coastal plain of Marathon, home to "
        "the ancient Battle of Marathon in 490 BCE where Greek forces famously defeated a Persian "
        "invasion — a location saturated with historical meaning that lends additional resonance "
        "to the modern engineering works. For the first half of the twentieth century, Marathon "
        "was the sole water source for Athens, a responsibility that required careful management "
        "during drought years and drove the city's early investment in water infrastructure. As "
        "larger reservoirs such as Mornos and Yliki came online, Marathon's role shifted from "
        "primary supply to an important secondary source and emergency reserve. Today, the dam "
        "functions as a backup component within the integrated Athens water system, contributing "
        "volume during wet years and available as a final reserve during acute shortage periods. "
        "The marble-faced structure and historic significance have made Marathon a destination "
        "for visitors interested in engineering heritage, water history, and the classical "
        "archaeology of Attica. In the context of contemporary water scarcity across Greece, "
        "Marathon represents both the pioneering efforts of earlier generations to secure Athens's "
        "water future and the enduring importance of every available water source in a warming "
        "and drying region."
    ),
}


def get_gr_dam_description(name_en: str) -> str:
    """Return the prose description for a Greek dam, or empty string if not found."""
    return GR_DAM_DESCRIPTIONS.get(name_en, "")
