"""
Unique prose descriptions for Sicily's 13 major reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.
Sicily faces chronic water scarcity driven by its semi-arid Mediterranean climate,
poorly distributed rainfall concentrated in winter, and high summer evaporation.
The island's reservoirs are essential for irrigation, municipal supply, and industry.
"""
from __future__ import annotations

IT_DAM_DESCRIPTIONS: dict[str, str] = {
    "Ancipa": (
        "The Ancipa reservoir sits in the Nebrodi Mountains of north-central Sicily, "
        "impounding the waters of the Troina river at an elevation that provides a "
        "commanding view of the surrounding volcanic landscape dominated by Mount Etna "
        "to the east. Completed in 1953, the gravity dam stands 105 metres tall and "
        "holds a total capacity of 30.4 million cubic metres. Ancipa plays a vital "
        "dual role: it supplies drinking water to the city of Catania and feeds the "
        "turbines of the adjacent hydroelectric power station, making it one of "
        "Sicily's most strategically important water assets. The reservoir collects "
        "runoff from the high Nebrodi terrain, where winter rainfall and snowmelt "
        "recharge the basin each year. The surrounding landscape of beech and oak "
        "forests is part of the Nebrodi Natural Park, one of the largest protected "
        "areas in Sicily. Water scarcity has historically affected the Catania region "
        "during prolonged droughts, and Ancipa's levels are closely monitored by "
        "regional authorities. The reservoir is named after the mountain plateau "
        "beneath which it sits, a windswept upland that experiences cold winters "
        "unusual for Sicily."
    ),
    "Pozzillo": (
        "Pozzillo is the largest reservoir in Sicily by authorized capacity, "
        "impounding 150 million cubic metres of water from the Salso river near "
        "Centuripe in the province of Enna. The earthfill dam was completed in 1959 "
        "and stands 56 metres above the valley floor. Located in central Sicily's "
        "agricultural heartland, Pozzillo is the backbone of the irrigation "
        "infrastructure that supports the vast citrus, olive, and cereal farms of "
        "the Catania and Enna provinces. The reservoir serves the Consortia of "
        "Reclamation that distribute water to thousands of smallholdings across the "
        "interior of the island. In drought years — which have become increasingly "
        "frequent under climate change — Pozzillo's levels determine whether summer "
        "crops survive or fail across a wide swath of eastern Sicily. The Salso, "
        "also known as the Imera Meridionale, is one of Sicily's longest rivers, "
        "rising near Enna and flowing south to the Mediterranean. Its catchment "
        "encompasses a predominantly clay landscape prone to erosion, which "
        "historically delivered significant silt loads to the reservoir. Pozzillo's "
        "strategic importance makes it the reference point for assessing the island's "
        "overall water security each summer."
    ),
    "Ogliastro": (
        "The Ogliastro reservoir was completed in 1986 on a tributary of the Imera "
        "Meridionale river in the province of Caltanissetta, representing one of "
        "Sicily's more recent large impoundments. With a capacity of 110 million "
        "cubic metres, the earthfill dam at 60 metres height was designed to "
        "supplement the existing reservoir network in central Sicily and improve "
        "water availability for the historically water-stressed interior communities. "
        "The reservoir collects drainage from the rugged clay hills of central "
        "Sicily, an area characterised by sparse vegetation, gully erosion, and "
        "highly variable seasonal rainfall. Og liastro supports irrigation for the "
        "agricultural zones of Caltanissetta province and contributes to the "
        "regional aqueduct supply. The construction of Ogliastro was part of a "
        "broader 1970s-1980s programme to expand Sicily's water storage capacity "
        "in response to growing demand from agriculture and urban populations. "
        "Like most Sicilian reservoirs, Ogliastro faces challenges from siltation "
        "and from the increasing intensity of drought periods that characterise "
        "the modern Mediterranean climate."
    ),
    "Prizzi": (
        "The Prizzi reservoir stands on the upper reaches of the Sosio river "
        "near the town of the same name in the Palermo hinterland, an area of "
        "rugged limestone hills that forms part of the Sicani mountain system. "
        "Completed in 1975 with a capacity of 10 million cubic metres, the "
        "earthfill dam at 50 metres height was conceived to serve local municipal "
        "water needs in the south-western Palermo province. The Prizzi basin "
        "collects winter rains from the Sicani uplands, where rainfall is higher "
        "than the Sicilian coastal average but still highly variable from year to "
        "year. The reservoir is part of the integrated water system managed by "
        "the Sicilian Basin Authority, which coordinates allocations among "
        "agriculture, municipal supply, and industrial uses across the western "
        "interior of the island. The town of Prizzi itself has been historically "
        "vulnerable to water shortages in summer months, and the reservoir "
        "provides a critical buffer against the annual dry season. The surrounding "
        "landscape retains patches of Mediterranean maquis and woodland, with "
        "views across the Sosio valley towards the coast."
    ),
    "Fanaco": (
        "The Fanaco reservoir sits in the upper Platani river valley in the "
        "province of Agrigento, completed in 1981 with a capacity of 21 million "
        "cubic metres. The earthfill dam rises 68 metres in a landscape of "
        "limestone ridges and terraced hillside farms that typify the central "
        "Sicilian interior. Fanaco was built to improve water availability for "
        "irrigation in the lower Platani valley, one of the most important "
        "agricultural corridors in western Sicily, where wheat, almonds, and "
        "olives are the dominant crops. The Platani river, the longest in western "
        "Sicily, has an irregular regime strongly influenced by winter rainfall "
        "and long dry summers, making regulated storage essential for year-round "
        "agricultural supply. The reservoir works in coordination with the nearby "
        "Castello dam system to maximise use of available runoff. Fanaco has "
        "experienced periods of severe drawdown during extended droughts, exposing "
        "the shoreline to erosion and concentrating pollutants from agricultural "
        "runoff. The reservoir is surrounded by the quiet agricultural villages "
        "of the Agrigento hinterland, where water availability remains a "
        "persistent concern for local farmers."
    ),
    "Gammauta": (
        "Gammauta is a small reservoir on a tributary of the Magazzolo river in "
        "western Sicily, near the town of Burgio in the province of Agrigento. "
        "Completed in 1964 with a capacity of 7 million cubic metres, the "
        "earthfill dam at 50 metres height was one of several smaller impoundments "
        "built in the 1960s to serve the water needs of rural communities in "
        "western Sicily. Despite its modest size, Gammauta plays an important "
        "local role in providing drinking water to communities in the Ribera and "
        "Sciacca areas and supporting small-scale irrigation in the Magazzolo "
        "valley. The reservoir basin collects runoff from the low limestone hills "
        "of western Sicily, an area of thin soils and sparse scrubland. Gammauta "
        "is one of the reservoirs most vulnerable to drought drawdown in Sicily's "
        "increasingly volatile water years: its small capacity means that even "
        "moderate rainfall deficits can reduce storage to critical levels. "
        "The Magazzolo river flows south through an agricultural landscape of "
        "vineyards, olives, and market gardens before reaching the Mediterranean "
        "near Ribera."
    ),
    "Leone": (
        "The Leone reservoir impounds a tributary of the Belice river in the "
        "province of Palermo, near the town of Bisacquino in the Sicani mountain "
        "foothills. Completed in 1971 with a total capacity of 7 million cubic "
        "metres, the earthfill dam rises 45 metres above the valley floor. Leone "
        "was designed to serve the municipal water needs of communities in the "
        "Corleone district and to support modest irrigation in the mid-Belice "
        "valley. The reservoir sits in a green valley surrounded by oak woodland "
        "and agricultural land, with the silhouette of the Sicani Mountains forming "
        "the backdrop. The Belice river system drains a wide area of western "
        "Sicily before emptying into the Mediterranean south of Marinella di "
        "Selinunte. In 1968 the region suffered the devastating Belice earthquake, "
        "and the subsequent reconstruction of valley communities created a renewed "
        "demand for reliable water infrastructure of which Leone formed part. The "
        "reservoir collaborates with the larger Garcia dam downstream to manage "
        "water resources across the Belice catchment."
    ),
    "Garcia": (
        "Garcia is the largest reservoir in western Sicily, impounding 64 million "
        "cubic metres of the Belice river near Campobello di Licata in the "
        "province of Palermo. Completed in 1990, the earthfill dam stands 51 "
        "metres high and was conceived as the linchpin of western Sicily's water "
        "supply system, serving both municipal needs and the extensive irrigation "
        "demands of the Belice valley's greenhouse and open-field agriculture. "
        "The Garcia reservoir is the focal point of the Belice Sinistro irrigation "
        "consortium, which distributes water to thousands of agricultural users "
        "across Palermo and Trapani provinces. The Belice river, fed by tributaries "
        "from the Sicani and Carboi mountains, delivers most of its annual flow "
        "during winter and early spring, making regulation essential for summer "
        "agriculture. Garcia works in coordination with the smaller upstream "
        "reservoirs of Leone and Piana degli Albanesi to maximise the capture "
        "and distribution of available water resources. In drought years the "
        "reservoir's level becomes a closely watched indicator of whether the "
        "region's farmers will face water rationing."
    ),
    "Piana degli Albanesi": (
        "The Piana degli Albanesi reservoir is one of the oldest in Sicily, "
        "completed in 1923 to supply drinking water to the city of Palermo. "
        "Located near the Arbëreshë community of Piana degli Albanesi — a "
        "town preserving Albanian language and Byzantine rite traditions since "
        "the 15th century — the earthfill dam at 50 metres holds 31 million "
        "cubic metres. For decades it was the primary water source for the "
        "Palermo metropolitan area, serving as evidence of early 20th-century "
        "engineering investment in Sicilian water infrastructure. The reservoir "
        "sits in a fertile elevated plain at about 720 metres above sea level, "
        "surrounded by agricultural land where winter wheat and market gardens "
        "have been cultivated for centuries. Today it remains part of the "
        "Palermo supply system alongside more modern sources, and it continues "
        "to support local irrigation. The surrounding landscape is one of the "
        "most scenic in western Sicily, with the reservoir reflecting the "
        "outline of Monte Kumeta to the south. The dam's age means its "
        "infrastructure requires ongoing maintenance vigilance."
    ),
    "Scanzano": (
        "Scanzano is a small dam on the Eleuterio river east of Palermo, "
        "completed in 1931 with a capacity of just 2.6 million cubic metres. "
        "The gravity dam at 25 metres height was one of the early public water "
        "works built to supplement Palermo's supply as the city's population "
        "grew in the early 20th century. Though modest in size, Scanzano "
        "occupies an important position in the Eleuterio catchment, a short "
        "river draining the limestone mountains of the Palermo hinterland. "
        "The reservoir collects winter rainfall from the foothills northeast "
        "of the Cozzo di Lupo ridge and provides a local buffer for the "
        "communities of the Palermo coast. Scanzano's small capacity makes it "
        "particularly sensitive to drought: in dry years the reservoir may "
        "approach empty before winter rains refill it. The Eleuterio valley "
        "is known for its scenic beauty, with rocky gorges, Mediterranean "
        "scrubland, and a rich bird life that includes birds of prey using "
        "the thermal currents above the cliffs. Despite its age, Scanzano "
        "remains part of the active water supply network for the metropolitan "
        "area of Palermo."
    ),
    "Rosamarina": (
        "Rosamarina is a large earthfill reservoir on the San Leonardo river "
        "in the province of Palermo, completed in 1996 and one of the most "
        "recently built of Sicily's major dams. With a capacity of 100 million "
        "cubic metres and standing 75 metres tall, Rosamarina was designed to "
        "address Palermo's chronic water supply shortfalls by tapping the San "
        "Leonardo catchment in the Madonie and Nebrodi mountain foothills. "
        "The reservoir supplies drinking water to Palermo and a belt of coastal "
        "towns, and it also supports irrigation in the broad valley between the "
        "Termini Imerese coast and the Madonie massif. The San Leonardo river "
        "drains a diverse landscape of limestone karst, agricultural terraces, "
        "and remaining patches of Mediterranean woodland. Rosamarina's relatively "
        "recent construction means its infrastructure is in better condition than "
        "older Sicilian dams, but it too faces challenges from sedimentation and "
        "from the trend towards lower and more erratic rainfall that climate "
        "projections suggest will continue through the 21st century. The "
        "reservoir has become a significant water body in the landscape, "
        "attracting wetland birds and providing a recreational amenity for "
        "the surrounding communities."
    ),
    "Cimia": (
        "The Cimia reservoir stands on the Dirillo river in the province of "
        "Ragusa in south-eastern Sicily, near the Comiso plateau. Completed "
        "in 1977 with a capacity of 12 million cubic metres, the earthfill "
        "dam rises 55 metres above the Dirillo valley floor. Cimia serves "
        "agricultural and municipal water needs in the Ragusa province, one "
        "of Sicily's most economically active zones, known for its extensive "
        "greenhouse cultivation of early vegetables and for its Ragusano DOP "
        "cheese production that requires reliable irrigation and livestock water. "
        "The Dirillo river flows through a landscape of limestone plateaux and "
        "clay valleys characteristic of south-eastern Sicily, collecting winter "
        "rainfall before turning south towards the Gulf of Gela. Cimia works "
        "in tandem with the smaller Ragoleto reservoir downstream to optimise "
        "use of the Dirillo's flow. The area around the reservoir is part of "
        "Sicily's most intensively farmed zone, and water availability directly "
        "determines the output and viability of the region's export-oriented "
        "horticultural sector."
    ),
    "Ragoleto": (
        "Ragoleto is the smallest reservoir in the Sicily monitoring network, "
        "impounding just 2.5 million cubic metres on a tributary of the Dirillo "
        "river in the province of Ragusa. The 30-metre gravity dam was completed "
        "in 1965 and serves local irrigation and water supply needs in the "
        "south-eastern corner of Sicily near the town of Acate. Despite its "
        "small size, Ragoleto plays a role in the integrated management of the "
        "Dirillo catchment, working alongside the larger Cimia reservoir upstream "
        "to provide a downstream buffer for agricultural users along the lower "
        "river. The area around Ragoleto is part of Sicily's most productive "
        "agricultural zone, where greenhouse cultivation of tomatoes, aubergines, "
        "and courgettes generates significant export revenues. Water availability "
        "in summer is critical for maintaining this intensive horticulture, and "
        "even a small reservoir like Ragoleto contributes to bridging the gap "
        "between winter rainfall and summer demand. The Dirillo river eventually "
        "empties into the Gulf of Gela, and its lower valley is flanked by some "
        "of the most important ancient Greek archaeological sites in Sicily, "
        "including Camarina."
    ),
}


def get_it_dam_description(name_en: str) -> str:
    """Return the prose description for a Sicilian reservoir.

    Falls back to a generic description if the dam is not in the dictionary,
    which guards against mismatches if the dam list is extended in future.
    """
    return IT_DAM_DESCRIPTIONS.get(
        name_en,
        (
            f"{name_en} is one of Sicily's reservoirs managed by the "
            "Sicilian Basin Authority (Autorità di Bacino della Sicilia). "
            "It forms part of the island's water supply network serving "
            "agricultural irrigation, municipal consumption, and industrial needs "
            "across a region characterised by a semi-arid Mediterranean climate "
            "with limited and highly seasonal rainfall."
        ),
    )
