"""
Unique prose descriptions for Poland's 15 major reservoirs.
Used on dam detail pages to provide SEO-friendly, human-readable context.
"""
from __future__ import annotations

PL_DAM_DESCRIPTIONS: dict[str, str] = {
    "Solina": (
        "The Solina reservoir in southeastern Poland's Bieszczady foothills is the "
        "country's largest by volume, holding 472 million cubic metres of water when "
        "full. Completed in 1968, the 82-metre concrete buttress dam spans the San "
        "river valley near the village of Solina in Podkarpackie province. The project "
        "required the resettlement of around 6,000 people from seventeen villages that "
        "were submerged as the reservoir filled. Today Solina is the centrepiece of a "
        "pumped-storage hydroelectric complex that provides critical peak-load capacity "
        "for the Polish national grid, with turbines capable of generating up to "
        "200 megawatts. The reservoir extends for 27 kilometres upstream along the "
        "San valley and up the Solinka tributary, with maximum depths exceeding "
        "60 metres. The surrounding Bieszczady mountains — part of the Outer Eastern "
        "Carpathians — are one of the most pristine wilderness areas in Central Europe, "
        "home to wolf, brown bear, Eurasian lynx, and European bison reintroduced from "
        "Białowieża. The Solina reservoir and the adjacent Bieszczady National Park "
        "together form a major ecotourism and recreation destination, with sailing, "
        "powerboat racing, and lakeside resorts at Polańczyk and Wołkowyja. Water "
        "quality is generally good due to the sparsely populated and largely forested "
        "catchment, though phosphorus inputs from agricultural land near the headwaters "
        "require ongoing monitoring."
    ),
    "Wloclawek": (
        "The Włocławek reservoir on the Vistula river in Kuyavian-Pomeranian province "
        "is one of Poland's largest water bodies, holding 453.6 million cubic metres. "
        "Completed in 1970, the low 14-metre run-of-river weir dam stretches 680 metres "
        "across the Vistula at the town of Włocławek, creating a 75-kilometre-long "
        "reservoir upstream. The primary purpose of the dam is hydroelectric generation: "
        "the eight Kaplan turbines produce up to 162 megawatts, making it Poland's "
        "largest operational hydropower station. The reservoir also provides navigation "
        "conditions on the upper Vistula and regulates downstream water flows. However, "
        "the dam has been ecologically controversial for decades because it blocks the "
        "migration of European sea trout and vimba bream, and has altered the sediment "
        "dynamics of the lower Vistula, contributing to riverbed erosion downstream. "
        "A planned second dam at Siarzewo downstream has been debated since the 1980s "
        "to address the hydraulic imbalance created by Włocławek but faces significant "
        "environmental opposition. The reservoir's shores are lined with willows and "
        "riverine forest habitats that support cormorant colonies, grey heron, and "
        "wintering populations of goldeneye and pochard. Urban recreation areas "
        "including marinas and beaches serve the Włocławek and Płock populations."
    ),
    "Czorsztyn": (
        "The Czorsztyn reservoir in the Pieniny mountains of Lesser Poland holds "
        "238.6 million cubic metres and was completed in 1997 after more than "
        "30 years of planning, controversy, and construction delays. The 56-metre "
        "concrete-face rockfill dam spans the Dunajec gorge near Czorsztyn castle, "
        "a medieval fortification that now rises dramatically above the reservoir "
        "shoreline. The project was intensely debated due to its proximity to the "
        "Pieniny National Park — one of Poland's smallest but most scenic protected "
        "areas — and the requirement to relocate more than 1,000 families from "
        "submerged villages. The reservoir was constructed primarily for flood "
        "protection of the Kraków and Nowy Sącz region against the highly variable "
        "Dunajec floods, which historically caused catastrophic damage downstream. "
        "Hydroelectric generation at the adjacent Niedzica power plant provides up "
        "to 92 megawatts. The sister reservoir of Sromowce Wyżne immediately "
        "downstream forms a tandem system. Today the Czorsztyn lake is a major "
        "tourist destination with windsurfing, kayaking, and guided boat tours to "
        "the medieval castle ruins. The traditional Dunajec gorge rafting route "
        "operated by Pieniny highland rafters begins immediately below the Sromowce "
        "dam and remains a beloved tourist experience."
    ),
    "Jeziorsko": (
        "The Jeziorsko reservoir on the Warta river in Łódź province holds "
        "193.1 million cubic metres, making it the largest reservoir in central "
        "Poland. Completed in 1986, the low 14-metre earth embankment dam near "
        "Warta town creates an unusually shallow but extensive water body — the "
        "reservoir covers approximately 4,200 hectares with an average depth of "
        "only 3.4 metres, giving it a distinctly lake-like character. The primary "
        "purpose is flood control on the Warta and Ner rivers protecting the "
        "Sieradz and Kalisz regions, combined with water supply augmentation "
        "for industry and navigation. The shallow, nutrient-rich water body has "
        "become an internationally important wetland for migratory waterbirds: "
        "the Jeziorsko reservoir is designated as a Special Protection Area under "
        "the EU Birds Directive, with more than 230 recorded bird species. During "
        "spring and autumn migration, the extensive mudflats exposed by reservoir "
        "drawdown attract spectacular concentrations of waders, including rare "
        "species such as broad-billed sandpiper and white-rumped sandpiper. "
        "Breeding colonies include great cormorant, grey heron, common tern, "
        "and penduline tit. The reservoir is a popular angling destination and "
        "hosts national rowing competitions on its sheltered southern bays. "
        "Eutrophication management is ongoing due to agricultural nutrient inputs "
        "from the intensively farmed Warta catchment."
    ),
    "Goczalkowice": (
        "The Goczałkowice reservoir on the upper Vistula near Pszczyna in Silesia "
        "holds 161.3 million cubic metres of water and has been supplying drinking "
        "water to the Katowice conurbation since its completion in 1956. The low "
        "15-metre earth-fill embankment dam creates a broad, shallow reservoir "
        "covering approximately 3,200 hectares in the Silesian Foothills between "
        "the Vistula and Bajerka rivers. The reservoir was one of the first large "
        "infrastructure projects in People's Republic of Poland designed specifically "
        "to address the chronic water shortage of the Upper Silesian industrial "
        "basin, which supports one of Europe's highest concentrations of heavy "
        "industry and population density. Today the Goczałkowice reservoir forms "
        "the backbone of the water supply network for the Katowice-Rybnik-Bielsko "
        "metropolitan area, serving approximately 2 million people. Water quality "
        "management is demanding: the reservoir receives inputs from the intensively "
        "agricultural Foothills catchment as well as treated municipal wastewater, "
        "requiring continuous phytoplankton and cyanobacteria monitoring. The "
        "extensive shallow zones support breeding little bittern, marsh harrier, "
        "and great reed warbler, and the reservoir is designated as a Natura 2000 "
        "site. Recreational access to the shoreline is restricted in the water "
        "protection zone, though some angling is permitted under licence."
    ),
    "Swinna-Poreba": (
        "The Świnna Poręba reservoir on the Skawa river in Lesser Poland is one "
        "of Poland's most recently completed large reservoirs, formally inaugurated "
        "in 2011 after a 35-year construction process beset by funding interruptions, "
        "engineering revisions, and the political transition from communist to "
        "democratic Poland. The 55-metre concrete-face rockfill dam holds "
        "160.8 million cubic metres in a deeply incised Carpathian foothill valley "
        "near Wadowice — the birthplace of Pope John Paul II. The reservoir serves "
        "multiple purposes: flood protection for the Skawa and upper Vistula valley, "
        "drinking water supply for the Kraków metropolitan area and southern Lesser "
        "Poland, low-flow augmentation for downstream navigation and ecology, and "
        "limited hydroelectric generation of approximately 4 megawatts. The long "
        "construction timeline meant several design revisions were required as "
        "geological investigations revealed challenging valley conditions. The "
        "reservoir displaced several hundred households from the Świnna Poręba "
        "and adjacent villages during filling. Today the water body extends "
        "12 kilometres upstream along the Skawa valley into the Beskid Makowski "
        "highlands, with forested hillsides providing a relatively clean and "
        "well-protected catchment. Recreation is developing gradually with "
        "fishing, kayaking, and shoreline walking trails established since 2013."
    ),
    "Roznow": (
        "The Rożnów reservoir on the Dunajec river in Lesser Poland holds "
        "155.8 million cubic metres and was completed in 1941 under German "
        "occupation during the Second World War — one of the few major "
        "infrastructure projects completed in occupied Poland during the conflict. "
        "The 40-metre concrete gravity dam near Rożnów in Małopolska impounds the "
        "Dunajec upstream of its junction with the Stradomka river, creating a "
        "22-kilometre reservoir in the rolling foothills of the outer Carpathians. "
        "The dam's construction forcibly displaced thousands of villagers and "
        "submerged numerous settlements. Today the reservoir is operated by "
        "Polskie Sieci Elektroenergetyczne for hydroelectric generation up to "
        "50 megawatts, and also provides flood control attenuation for the "
        "Nowy Sącz region downstream. The smaller Czchów reservoir forms a "
        "downstream tandem with Rożnów. Angling — particularly for catfish, "
        "carp, and pike-perch — is the primary recreational use, and the "
        "Rożnów-Czchów lake complex is popular with boat anglers from the "
        "Kraków-Tarnów area. Ecological monitoring shows that sediment "
        "trapping behind the dam has significantly reduced gravel bed "
        "replenishment in the Dunajec downstream, affecting habitat for "
        "spawning fish. Fish passage facilities were retrofitted but their "
        "effectiveness remains limited for upstream salmon migration."
    ),
    "Dobczyce": (
        "The Dobczyce reservoir on the Raba river holds 137.7 million cubic metres "
        "and serves as the primary drinking water source for the Kraków metropolitan "
        "area. Completed in 1986, the 42-metre earth and rockfill dam near Dobczyce "
        "in the Małopolska Foothills stores water from the Raba catchment in the "
        "Beskid Wyspowy mountains. The reservoir provides approximately 60 percent "
        "of Kraków's drinking water needs, serving a city of around 800,000 people "
        "plus surrounding communities, making it one of the most strategically "
        "important water sources in Poland. The catchment protection regime is "
        "correspondingly strict: a multi-zone buffer protects the reservoir from "
        "agricultural runoff, and the Raba National Drinking Water Protected Area "
        "covers most of the upper Raba valley. The water quality is generally "
        "good, though seasonal variations in turbidity occur during heavy Carpathian "
        "snowmelt and summer storms. A water treatment plant at Dobczyce processes "
        "the raw reservoir water before distribution. The reservoir valley is "
        "flanked by scenic Foothills landscapes with traditional villages, "
        "orchards, and church architecture typical of Lesser Poland. Recreational "
        "activities are limited by the water protection regulations, though angling "
        "is permitted in designated zones with strictly enforced licensing."
    ),
    "Otmuchow": (
        "The Otmuchów reservoir on the Nysa Kłodzka river in Lower Silesia holds "
        "129.2 million cubic metres and was completed in 1933, making it one of "
        "Poland's oldest large reservoirs. The 25-metre earth embankment dam at "
        "Otmuchów in Opolskie province was built by the German regional authorities "
        "of Upper Silesia for flood control on the historically flood-prone Nysa "
        "Kłodzka. The reservoir works in tandem with the Nysa reservoir downstream, "
        "and together they regulate the Nysa Kłodzka river through the Opole "
        "region where devastating floods occurred repeatedly in the 19th and early "
        "20th centuries. The 1997 millennium flood — the most severe in recorded "
        "Polish history — demonstrated the critical role of both reservoirs in "
        "mitigating peak flows, though even their combined retention capacity was "
        "overtopped by that exceptional event. Today Otmuchów also provides "
        "recreation: the reservoir shoreline near Otmuchów town has beaches, "
        "sailing infrastructure, and camping, making it one of the most popular "
        "summer destinations in Lower Silesia. The relatively warm, shallow bays "
        "on the reservoir's southern shore develop significant aquatic vegetation "
        "and support breeding great crested grebe and numerous surface-nesting "
        "ducks. The surrounding agricultural landscape of the Sudeten Foreland "
        "is characterised by fertile loess soils and mixed farming."
    ),
    "Nysa": (
        "The Nysa reservoir on the Nysa Kłodzka river in Lower Silesia holds "
        "121.7 million cubic metres and forms the downstream partner to the older "
        "Otmuchów reservoir immediately upstream. Completed in 1971, the 36-metre "
        "concrete gravity dam near the town of Nysa in Opolskie province serves "
        "primarily for flood control, water supply to the Opole and Nysa urban "
        "areas, and recreational provision. The two-reservoir system on the Nysa "
        "Kłodzka provides coordinated flood retention capacity for the Sudeten "
        "Foreland, a region historically subject to flash flooding from the steep "
        "Sudeten Mountain catchments following heavy rainfall or rapid snowmelt. "
        "The Nysa reservoir's warm, moderately eutrophic waters make it a popular "
        "recreation spot: the Nysa camping and beach complex on the western shore "
        "is one of the largest and best-developed in Lower Silesia, attracting "
        "visitors from the Wrocław conurbation 80 kilometres to the north. "
        "Windsurfing, sailing, motorboat racing, and freshwater angling are all "
        "practised on the reservoir. Ecological surveys document populations of "
        "great cormorant, night heron, and various migratory waterfowl using "
        "the reservoir during spring and autumn passage. The surrounding Sudeten "
        "Foreland agricultural landscape is known for its traditional Silesian "
        "village architecture and orchards of Silesian prune plum."
    ),
    "Debe": (
        "The Dębe reservoir on the Bug river in Masovia holds 96 million cubic "
        "metres and was completed in 1963 — one of the first large reservoirs built "
        "in People's Republic of Poland after the Second World War. The 17-metre "
        "concrete and earthfill weir dam at Dębe village north of Warsaw on the "
        "Narew river (which carries Bug river water at this confluence) creates a "
        "shallow, meandering reservoir that extends some 30 kilometres upstream. "
        "The Dębe reservoir forms the upper element of the Zegrzyński reservoir "
        "system, which serves as the primary backup drinking water source for the "
        "Warsaw metropolitan area. Its main functions are water supply regulation, "
        "flood attenuation on the Narew-Bug system, and hydroelectric generation "
        "of approximately 5 megawatts. The reservoir — known locally as the "
        "Zalew Zegrzyński — is extremely popular for recreation given its proximity "
        "to Warsaw: sailing clubs, water skiing, rowing, beach areas, and "
        "weekend cottages line the extensive shoreline, and it is estimated to "
        "receive over one million visitor days per year. Water quality management "
        "is challenging: intensive recreation, agricultural runoff from the Bug "
        "catchment, and treated wastewater inputs create eutrophic conditions with "
        "frequent algal blooms in summer. Cyanobacterial warnings are issued most "
        "summers, temporarily restricting swimming access."
    ),
    "Tresna": (
        "The Tresna reservoir on the Soła river in Lesser Poland holds 92.7 million "
        "cubic metres and was completed in 1966 as the uppermost of three cascading "
        "reservoirs on the Soła: Tresna, Porąbka, and Czaniec. The 46-metre concrete "
        "and earthfill dam near Bielsko-Biała impounds the Soła river in the Beskid "
        "Mały foothills, creating a reservoir that extends 12 kilometres upstream "
        "into the Beskid Śląski mountains. The Soła cascade was built to harness "
        "the hydroelectric potential of the steep Carpathian rivers flowing north "
        "from the Silesian Beskids and to provide water supply and flood protection "
        "for the Bielsko-Biała and Oświęcim industrial areas. Together the three "
        "reservoirs generate approximately 92 megawatts of hydroelectric power. "
        "The Tresna reservoir is operated by Tauron Polska Energia and forms part "
        "of the Vistula catchment flood management system. The Żywiec basin upstream "
        "is known for its traditional Highlander (Góral) culture, breweries, and "
        "landscape of forested mountains and valley villages. Tresna's relatively "
        "clean Carpathian water and scenic setting attract sailing and recreation. "
        "The adjacent Żywiec brewery draws significant tourist interest to the region. "
        "Otters have been documented returning to the Soła river below the dam as "
        "water quality has improved following industrial restructuring in the region."
    ),
    "Turawa": (
        "The Turawa reservoir on the Mała Panew river in Opole Silesia holds "
        "92.6 million cubic metres and was completed in 1938 under the German "
        "administrative authorities of Upper Silesia — one of the first large "
        "reservoirs built in what is today Polish territory. The 23-metre earth "
        "embankment dam near Turawa in Opolskie province creates a broad, shallow "
        "reservoir covering approximately 2,200 hectares in the Silesian Lowland "
        "forest landscape. The reservoir was originally built for flood control "
        "on the Mała Panew and Odra rivers, and for water supply to the Upper "
        "Silesian industrial district. Today it serves primarily as a recreational "
        "reservoir and flood buffer. The Turawa lake complex is one of the most "
        "popular recreation destinations in Opolskie province, with three beach "
        "areas, extensive sailing and rowing infrastructure, camping sites, and "
        "surrounding forests ideal for cycling and walking. The water body is "
        "separated into two basins by a causeway and bridge: the larger main "
        "reservoir and the smaller Mały Turawa. The shallow, warm water of the "
        "main reservoir is highly eutrophic and subject to annual cyanobacterial "
        "blooms that restrict bathing during peak summer weeks. The surrounding "
        "Turawa forest park, covering over 5,000 hectares of Scots pine and oak, "
        "provides habitat for red deer, wild boar, and breeding ospreys."
    ),
    "Sulejow": (
        "The Sulejów reservoir on the Pilica river in Łódź province holds "
        "84.3 million cubic metres and was completed in 1973 as the main water "
        "supply reservoir for the Łódź metropolitan area. The 17-metre earth "
        "embankment dam near Sulejów town in central Poland creates an unusually "
        "long and meandering reservoir — extending some 27 kilometres upstream "
        "through the Pilica river valley — with an average depth of only about "
        "3.5 metres due to the flat terrain of the central Polish lowlands. The "
        "reservoir supplies drinking water to Łódź, Poland's third largest city, "
        "via a treatment plant and extensive distribution network. It also provides "
        "flood attenuation for the Pilica valley and supports downstream ecological "
        "flows. The Sulejów reservoir and the surrounding Sulejów Landscape Park "
        "protect significant riverside forest habitats with extensive oak-hornbeam "
        "woodlands, riparian alder stands, and internationally important populations "
        "of the great grey owl and white-tailed eagle. The landscape park covers "
        "around 17,000 hectares and includes the ruins of the historic Cistercian "
        "abbey at Sulejów town — a 12th-century monument of national significance. "
        "Recreational fishing, kayaking, and cycling are popular activities on and "
        "around the reservoir. Eutrophication management is an ongoing challenge "
        "given agricultural nutrient inputs from the intensive farming landscape "
        "of the Pilica catchment."
    ),
    "Dzierzno-Duze": (
        "The Dzierżno Duże reservoir on the Kłodnica river in Upper Silesia holds "
        "84.3 million cubic metres and occupies an unusual setting — a man-made "
        "reservoir in one of Europe's most heavily industrialised landscapes. "
        "Completed in 1963, the 16-metre earth embankment dam near Pyskowice in "
        "the Silesian Metropolis GZM impounds the Kłodnica river, which drains "
        "the heart of the Upper Silesian Coal Basin. The reservoir was built for "
        "industrial water supply to the steelworks and chemical industry of "
        "Gliwice and Zabrze, and for flood control on the heavily modified "
        "Kłodnica. Its history is intertwined with the industrial transformation "
        "of Upper Silesia: during the communist era it supplied massive volumes "
        "of process water to heavy industry, and its water quality reflected "
        "severe industrial pollution. Since the post-1989 industrial restructuring "
        "and closure of many polluting facilities, water quality has improved "
        "substantially, though legacy contamination of sediments remains a concern. "
        "Today the Dzierżno Duże is primarily a recreational reservoir serving "
        "the dense population of the Silesian Metropolis: sailing, angling, and "
        "beach activities are popular on the northern shores near Pyskowice, and "
        "the adjacent Dzierżno Małe reservoir provides additional recreation "
        "space. The water body is an important stop for migratory waterbirds "
        "moving through the otherwise heavily built-up Silesian landscape."
    ),
}


def get_pl_dam_description(name_en: str) -> str:
    """Return the prose description for a Polish reservoir by its ASCII name_en key.

    Falls back to a generic placeholder if the key is not found — this avoids
    KeyErrors from data inconsistencies between the DB and description dict.
    """
    return PL_DAM_DESCRIPTIONS.get(
        name_en,
        f"{name_en} is a reservoir in Poland. Detailed information about this "
        "reservoir will be added in a future update.",
    )
